### ISSUE TITLE
Error in loading DLL when Building from Source

### ISSUE THREAD

**Issue by meichthys** [joyfullservice/msaccess-vcs-integration#109]
Very useful project! We've been doing something similar internally for a few years, but this is significantly more user friendly!

OS: Windows 10
Access: Access 2019 64bit (Desktop Version)

I am able to export without any issues, but when i try to build from source i receive the following error:
![image](https://user-images.githubusercontent.com/10717998/101075546-28ad7e00-3570-11eb-82aa-0fe44a9be3de.png)

When i debug it breaks here:
![image](https://user-images.githubusercontent.com/10717998/101075526-221f0680-3570-11eb-8afe-ea89b51d16e9.png)

**Comment by joyfullservice** [comment]
Thanks for reporting this! I have some recent updates in a development branch that address this problem. See #110 

In the mean time, you can add the following line to `clsDbVbeReference` to ignore errors when importing references.

![image](https://user-images.githubusercontent.com/7254992/101101350-f6ab1480-358d-11eb-9dd1-4a5d83253883.png)

**Comment by meichthys** [comment]
Wow, Thanks for the quick reply! It's great to see that it is already being addressed!
