### ISSUE TITLE
modDeploy.bas is not relevant to this project

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#11]
Deployment is a very different project from version control. I would not include these features in the VCS system at all. Another good reason not to include this module is that it contains system specific code that isn't included in the project.

**Comment by joyfullservice** [comment]
Yes, I agree. With the direction of transitioning this project into an add-in for Microsoft Access, instead of a file I include with each project, this deployment module will no longer be needed.

**Comment by joyfullservice** [comment]
This was closed in pull request #19
