### ISSUE TITLE
Log exceptions/errors rather than crashing

### ISSUE THREAD

**Issue by mmzmusicnotes** [joyfullservice/msaccess-vcs-integration#110]
Use a logger class to report loggers to the user via a logfile and continue executing.

**Comment by joyfullservice** [comment]
@mmzmusicnotes - I have added a new function today to simplify general error handling and logging. Here is a basic usage example:

![image](https://user-images.githubusercontent.com/7254992/101098142-09224f80-3588-11eb-918f-3f7246e2fc0e.png)

To me it seems more elegant to log the error and reset the error status in a single line without needing to include the entire `If` block inline with the code. It is perhaps less conventional, but seems more clear and readable, in my opinion.

The following code sample also shows the usage of a similar function `Catch` to trap a specific potentially expected error, followed by the `CatchAny` to log any other error. The source for both functions is also shown below.

```vba
'---------------------------------------------------------------------------------------
' Procedure : DeleteObject
' Author    : Adam Waller
' Date      : 11/23/2020
' Purpose   : Deletes the object if it exists. (Surpresses error)
'---------------------------------------------------------------------------------------
'
Public Sub DeleteObjectIfExists(intType As AcObjectType, strName As String)
    On Error Resume Next
    DoCmd.DeleteObject intType, strName
    Catch 7874 ' Object not found
    CatchAny "Deleting object " & strName
End Sub


'---------------------------------------------------------------------------------------
' Procedure : Catch
' Author    : Adam Waller
' Date      : 11/23/2020
' Purpose   : Returns true if the last error matches any of the passed error numbers,
'           : and clears the error object.
'---------------------------------------------------------------------------------------
'
Public Function Catch(ParamArray lngErrorNumbers()) As Boolean
    Dim intCnt As Integer
    For intCnt = LBound(lngErrorNumbers) To UBound(lngErrorNumbers)
        If lngErrorNumbers(intCnt) = Err.Number Then
            Err.Clear
            Catch = True
            Exit For
        End If
    Next intCnt
End Function


'---------------------------------------------------------------------------------------
' Procedure : CatchAny
' Author    : Adam Waller
' Date      : 12/3/2020
' Purpose   : Generic error handler with logging.
'---------------------------------------------------------------------------------------
'
Public Function CatchAny(Optional strSource As String, Optional blnLogError As Boolean = True, _
    Optional blnClearError As Boolean = True) As Boolean
    If Err Then
        If blnLogError Then Log.Add "Error " & Err.Number & ": " & Err.Description & _
            IIf(strSource <> vbNullString, " Source: " & strSource, vbNullString)
        If blnClearError Then Err.Clear
        CatchAny = True
    End If
End Function
```

**Comment by mmzmusicnotes** [comment]
This looks great, and I think it will do exactly what I want. I'll be back soon with more.

**Comment by A9G-Data-Droid** [comment]
Just be sure to always put `On Error Goto 0` after the catch so you're not skipping past further errors beyond your Try block.

**Comment by joyfullservice** [comment]
See further discussion on error handling [here](https://github.com/joyfullservice/msaccess-vcs-integration/commit/5fc2bd9fbdf088bc5b8e277bc338cfea944de69e#r46246407).

**Comment by joyfullservice** [comment]
This is now generally in place, although not necessarily fully implemented in all areas of the code. Based on the original purpose of this issue, I feel we have resolved the question of how to log errors and track the global state of errors during an export/build operation. Additionally, there is now an option to enable the add-in to break (stop to debug) on unhandled errors, which I think will help our ability to troubleshoot problems that users experience but are not easily reproducible.

At some point we should probably create a documentation page on the wiki that explains the approach we are taking with error handling since the inline approach (`Catch`, `CatchAny`, `DebugMode`) used in this project is different from the more traditional VBA boilerplate error handling.
