### ISSUE TITLE
Add-In cannot be installed

### ISSUE THREAD

**Issue by pwouters** [joyfullservice/msaccess-vcs-integration#114]
Installing the Add-in I get a message Add-in cannot be installed, Table USysReginfo is missing. In MS Access by the options the add-ins are visible but i can't install them.  What to do?

**Comment by joyfullservice** [comment]
To install the add-in, simply double-click the `Version Control.accda` file. It will launch the installer automatically.

**Comment by pwouters** [comment]
It's visible in Database Tools , I see it now.

**Comment by pwouters** [comment]
Thx Adam,

It’s working now.

Paul

Op zo 27 dec. 2020 om 15:34 schreef Adam Waller <notifications@github.com>

**Comment by joyfullservice** [comment]
I am glad to hear that it is working for you!
