### ISSUE TITLE
Export/Import Error causing crash and loss of log 

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#130]
When building file from source, if there's an error, Access will close unexpectedly, and the import log never shows up.

Does the log get saved periodically to somewhere one could export it?

**Comment by hecon5** [comment]
Ok, so I've stepped through (about ... many times). 

I think I've found the line that will immediately without notice crash Access (more on this in a bit).

This line will IMMEDIATELY crash Access without notice:
`Set objEnc = CreateObject("System.Security.Cryptography.SHA1CryptoServiceProvider")`

I set to early binding (referenced in https://stackoverflow.com/questions/46480687/excel-vba-sha1-function) and this STILL crashes even when the reference is loaded in.

Troubleshooting more to see if I can tweak this, but it is definitely causing me headaches.

**Comment by hecon5** [comment]
Note: I don't have encryption set up, and I'm not using git integration.

**Comment by joyfullservice** [comment]
As you have probably observed in the code, SHA1 is used to generate a hash of the contents of a VBA code module. This is important because a find-and-replace operation in VBA can update code _without_ changing the modified date of the underlying object. See #106 and 5a0d824. Storing the hash in our index file gives us a more reliable way to determine whether the VBA code has changed.

I believe this class is a pretty [standard](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha1cryptoserviceprovider?view=net-5.0) one in the .Net framework... I assume you are running on Windows 10 with .Net installed? What happens if you run this code from Excel VBA or VBScript?

**Comment by hecon5** [comment]
More research: https://github.com/lidgren/lidgren-network-gen3/issues/26  points to a similar issue I am prone to (FIPS is required on my system). 

mscorlib.dll is referenced in, and when I have that module in Excel, it works fine. Poking around to see what's going on that Access isn't allowed to call that now.

I'm trying to figure out how to step through this, and find a workaround / use SHA256 (which is) will keep troubleshooting and let you know.

**Comment by hecon5** [comment]
Ok, so, this is hilarious. It's caused by RubberDuck!
I was poking about in RD,and removed the mscorlib.dll reference via RD, and RD crashed. Out of curiosity, I unloaded it, recompiled, and now I can run it. 

I'm troubleshooting RD to figure out why it crashes on that line specifically and will update when I figure it out.

Huzzah!

I do have another question for you (and others): with SHA1 being broken, I'd humbly suggest that we move to SHA256 at a minimum, or something else. I realize this is reeeeeeal low probability and performance is in the balance, but this could also reduce the likelihood that someone would rely on the SHA1 function to provide a secure hash and would instead use an actually secure mechanism. 

Thoughts?

**Comment by joyfullservice** [comment]
@hecon5 - The reason I went with SHA1 is both for performance, and because that is what Git itself uses for comparing the contents of files. I figure that those software engineers have spent way more time than I will ever have to analyze performance and determine the best algorithm for detecting content changes. (But I must say that I enjoyed the research and learning about how git detects changes.)

We are not using SHA1 to secure anything (which is where we might run into issues with FIPS) but just to detect changes to files. The hashing functions are not exposed outside the project, so someone would have to be pretty intentional about using them elsewhere.

The fact that SHA1 seems to work for you in Excel is interesting. Do you encounter the crash on any other systems, or just your computer? Do you still get the crash after disabling all add-ins (i.e. RubberDuck, MZ-Tools, etc....) and after a clean reboot?

I am not opposed to exposing an option for the hash provider, (SHA1, SHA256, etc...) but it would be good to know that this is not just a workaround for a single system or an unrelated issue....  😄 

```
    Select Case Options.HashType
        Case "SHA1"
            Set objEnc = CreateObject("System.Security.Cryptography.SHA1CryptoServiceProvider")
        Case "SHA256"
            Set objEnc = CreateObject("System.Security.Cryptography.SHA256CryptoServiceProvider")
    End Select
```

**Comment by hecon5** [comment]
This is fair (and a good answer); though git is / was? moving away from SHA1 (https://git-scm.com/docs/hash-function-transition). (Aaaanyway, that's a deeeeep hole I don't want to go down at the moment while I figure out this particular stumbling block).

On to "my" problem: .net is looking more like a culprit, but /why/ it's a culprit is still evading me.

**Comment by hecon5** [comment]
(Some of this is documented just so if some poor user comes behind me they might be sped along) 

More digging has found others that look like similar instances https://github.com/VBA-tools/VBA-Web/issues/257
This illustrates a very similar issue I've got: older versions are not installed / removed. I'm looking into a way to reduce the dependency on the .NET hashing tool as a result and will update when I find more.

I've had several others in my environment try and run that same line. `Set objEnc = CreateObject("System.Security.Cryptography.SHA1CryptoServiceProvider")`, and it crashes their instances, too. Getting exception 0xc0000005; in Access only. I can run that in Excel and it works A-OK (go figure). 

This leads me to wonder if ... perhaps, Access has been given the "privilege" of being more restricted (or just not installed correctly) as it is a similar cause / symptom as #120.

**Comment by hecon5** [comment]
As I look through this: it looks like a way to handle this might be to build a new class that's standalone and doesn't rely on outside dependencies when using SHA256. 

For our projects, we use a class module which doesn't rely on .NET 3.5 (for this same reason); since it's already internal to VBA, it's not going to be as fast, and if a user wants SHA256 it's also likely they may have issues with dependencies so the loss of speed shouldn't be (as) noticeable. 

With that in mind; I think the option to use SHA256 should also use the internal class, this would eliminate the dependency where we need to, and speed things along where the dependency is not a limiter. 

Thoughts?

**Comment by hecon5** [comment]
(Diggin' a real deep hole here; hopefully this doesn't count as spam :)

I've found this hash relies on the OS and doesn't have a dependency to .NET 3.5; and [VB6 Hash Class - MD5 , SHA-1, SHA-256, SHA-384, SHA-512](http://khoiriyyah.blogspot.com/2012/06/vb6-hash-class-md5-sha-1-sha-256-sha.html), and [a VBA-Tools Thread comment](https://github.com/VBA-tools/VBA-Web/issues/257#issuecomment-386453928) Which @joyfullservice you've commented on previously ;) 

I'm going to rework the declarations to include 64 bit/VB7 compilation instructions and report back.

**Comment by hecon5** [comment]
@joyfullservice, IIRC, you use Office 2010, mind if I ask what OS you run on? One thing I've discovered in my travels this last week is  [MSFT Cryptography Functions](https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptography-functions) page appears to state the advpi32.dll functions in the aforementioned routines are being depreciated and may be removed in future versions of Windows. The page points you to [Cryptography API: Next Generation](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal) instead which uses BCrypt.dll. It looks like the Minimum OS is Win Vista, but wondered if this will be limiting?

**Comment by joyfullservice** [comment]
@hecon5 - I am running Windows 10 at home and work. Cryptography is actually what finally pushed me off Windows 7 when I could no longer connect to a WordPress API through VBA. 😢 Support for Win 7/8/10 is great, but I am okay with Windows 10 and newer, especially if this is just for the alternate crypto class. Thanks for your work on this!  😄

**Comment by hecon5** [comment]
Successfully compared hash between the internal SHA256 and the system bcrypt.dll calls! 

```VBA
Public Const hashInput As String = "GOODFELLA"

print_hashclsSHA256
HASHInternalcls:
150124114415780142348099229140301468924217223415521121211995151525522820675145114175

print_hashSHA256
HashSytem:
150124114415780142348099229140301468924217223415521121211995151525522820675145114175
```

**Comment by hecon5** [comment]
@joyfullservice So this is working in my instance; can you give the PR a review (and perhaps even give the new code a try in yours)?

It seems to work nicely. The only thing I think you might have an issue with is whether `NGHash` can input a longptr in Office 2010, but it can in 64bit. If not, I've found a workaround for that, too.

**Comment by joyfullservice** [comment]
Nice work on #135! I did some side-by-side testing comparison on both long and short strings, and the API version is faster and eliminates the .Net dependency. 😄 👍  I will go ahead and accept the PR and make a few tweaks. (Such as we don't need two versions of the API declarations since Access 2010 [supports](https://en.wikipedia.org/wiki/Visual_Basic_for_Applications) 64-bit declarations.)


```
Public Sub TestHashSpeed()

    Const cintTestCount As Integer = 1000
    
    Dim strData As String
    Dim intTime As Integer
    Dim strTest As String
    
    strData = ReadFile(CurrentProject.Path & "\Version Control_Backup.accda")
    'strData = CurrentProject.Path & "\Version Control_Backup.accda"

    With Perf
        .StartTiming
        
        For intTime = 1 To cintTestCount
            .OperationStart ".Net SHA1"
            strTest = modHash.GetStringHash(strData)
            .OperationEnd
            
            .OperationStart "API SHA1"
            strTest = modHashApi.GetStringHash(strData)
            .OperationEnd
        Next intTime
        
        .EndTiming
        Debug.Print .GetReports
    End With

End Sub

-------------------------------------
        PERFORMANCE REPORTS
-------------------------------------
Operations          Count     Seconds
-------------------------------------
.Net SHA1           1000      1.67
Compute SHA1        1000      13.93
API SHA1            1000      1.50
Compute SHA1 API    1000      11.48
Other Operations              0.11

```

**Comment by hecon5** [comment]
Sweet; This means we can remove the cruft for the .NET calls (I commented them out), and I was looking into the encryption tool, and since that also has encryption mechanisms, this could reduce the encryption deficiencies as well.

**Comment by hecon5** [comment]
One last thing about this: I didn't include the preferences for what hashing mechanism to use (SHA1 vs SHA256), because I didn't want to muddy this up with too many hooks at first; depending on how you want to incorporate the hash/encryption options, there are a few ways to go about that. If you don't find any other bugs, we can close this, and I can make a new issue to address the encryption components of this change.
