### ISSUE TITLE
Need to return hash for empty strings

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#136]
The updated `GetStringHash` function should return a digest for an empty string (`vbNullString`) Currently it throws an error for a subscript out of range.

![image](https://user-images.githubusercontent.com/7254992/105425232-92f8ab80-5c0e-11eb-9249-3facc6ee43fb.png)

Technically a call to this function should return a known digest. (See [this link](https://crypto.stackexchange.com/questions/26133/sha-256-hash-of-null-input))

**Comment by hecon5** [comment]
This is actually an issue with Lbound; I caught it just before you put this up. Working on a fix, unless you have a handy one.

**Comment by hecon5** [comment]
@joyfullservice fixed!

**Comment by hecon5** [comment]
As I poked through this; I noticed you truncate the hash...why?

**Comment by joyfullservice** [comment]
> As I poked through this; I noticed you truncate the hash...why?

Great question! This matches the display that Git uses with short hashes. (I.e. 5fc2bd9) It also keeps the index file smaller and perhaps a little more readable.

![image](https://user-images.githubusercontent.com/7254992/105512514-ce3ebd00-5c96-11eb-992c-cb9f50a54c05.png)

The probability of a collision is extremely rare, (especially in how we are using them) so my thought was to keep things simple, readable, and more consistent with the typical user experience with git.

**Comment by hecon5** [comment]
Perfect! Thought so, but I hate to assume when I can just ask and make sure :) Thanks!

**Comment by joyfullservice** [comment]
Closing out this issue as I believe it has been fully resolved.
