### ISSUE TITLE
Possibility to export all Access databases to a subfolder

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#139]
Hi,

in my folder "development" I have several accessdatabases (*.accdb) and I want to export them to a subfolder called "vcs"

accessdatabases - e.g:
db1.accdb
db2.accdb
db3.accdb

The exported databases should be saved in subfolder "vcs"
/vsc/db1.accdb.src/modules 
/vsc/db1.accdb.src/forms ....

/vsc/db2.accdb.src/modules 
/vsc/db2.accdb.src/forms ....

But if I set in "options" the "export folder" to "\vsc" the directory structur will be:
/vsc/modules 
/vsc/forms ....
the subfolder [databasename.accdb.src] in "vcs" is missing

**Wish:**
To have a placeholder (e.g. "%dbname%) in options --> "export folder" so I can build my own path.
"folder name" = "\vcs\%dbname%" 

**Result:**
Export folders will be 
/vsc/db1.accdb.src/modules 
/vsc/db1.accdb.src/forms ....

/vsc/db2.accdb.src/modules 
/vsc/db2.accdb.src/forms ....

**Comment by joyfullservice** [comment]
@Tanarri - I can see how this could be helpful when you want to use a custom relative export path, but don't want to have to set it manually for each database project.

Up to now, you could achieve the desired folder structure by specifying `\vcs\db1.accdb.src\` in the export folder path, but you would have to do this for each project.

With b9e84c5, you can now specify `\vcs\%dbName%.src\`, in your default options, and it should resolve to the desired path in each database you export without needing to change the Export Folder path for each project.

![image](https://user-images.githubusercontent.com/7254992/106010883-8b5a5c00-607f-11eb-8a97-3e6db367c55c.png)

![image](https://user-images.githubusercontent.com/7254992/106010896-8eede300-607f-11eb-92f9-c9ceb8080920.png)

_Note that I have added this commit to the `dev` branch, which will eventually roll out in version 3.3. If you are using the latest public release or building from the `master` branch, you will want to manually add this to your copy of the add-in._

**Comment by Tanarri** [comment]
Great! I am looking forward V3.3
