### ISSUE TITLE
New Feature: Allow export of single DB types in addition to "export All source"

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#141]
As the Ribbon Integration from @A9G-Data-Droid doesn't seem feasible as an addin, it'd be nice to add the different types of exports as single options; additionally, when exporting these, turn of the nag popup that says "you can remove the vcs modules" (or perhaps make this a separate option? 

While users switch over (such as myself), I'd like to leave the Legacy modules in place for a tad while we verify operation and train up our code team.

**Comment by hecon5** [comment]
Proposed options to add to to be inline with existing:
![image](https://user-images.githubusercontent.com/54177882/106159050-65ea5280-6152-11eb-82c2-d1d8babc7333.png)

I've grouped them to "similarish" types that one might be working on and want to export just these types:
1) Export Modules & Macros
2) Export Tables & Queries
3) Export Forms & Reports

I do think keeping build/import to require opening the addon popup is the right call, because I think it could have significant consequences (aka breaking the dev you're working on right now).

Perhaps when git integration is a little more polished, a "SYNC" would import/export changes to/from the source directory much like a merge so you'd be presented with any conflicts prior to deleting your work, but for now, adding a step of deliberate nature is a good thing.

**Comment by hecon5** [comment]
I just made a PR #158  for this that lays the ground work for this by way of making a standard entry handler and providing some different processing inputs. 

We'll still need to build export subs that will export just a few types, but this would make it a little easier to add commands; or not.

**Comment by joyfullservice** [comment]
I think the long-term solution here is to incorporate this into the (future) custom Access ribbon. That will allow people to customize their ribbon XML to best suit their needs and workflow. I am hesitant to add too many entries to the built-in add-ins menu, since this is also shared with other add-ins. I will go ahead and close this out for now, and we can revisit this as a part of integrating the add-in into a custom ribbon. (See #34)
