### ISSUE TITLE
"Build from Source": Import Image --> File not found 

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#142]
Hi,

I had exported my big project and all went fine.
On another computer I want to "build it from source".

It stopped with error 53 "File not found" on "cCategory.Import CStr(varFile)" in "modImportExpot.Build"

More infos for following codelines:
Module clsDBSharedImage.Import
```
        ' Check for an existing file with the same name
        strOriginalName = IDbComponent_BaseFolder & dItem("FileName")
        strImageFile = IDbComponent_BaseFolder & FSO.GetBaseName(strFile) & "." & FSO.GetExtensionName(strOriginalName)
        If strOriginalName <> strImageFile Then
            If FSO.FileExists(strOriginalName) Then
                strTemp = IDbComponent_BaseFolder & FSO.GetTempName
                ' Rename to temp file
                Name strOriginalName As strTemp
            End If
            Name strImageFile As strOriginalName
        End If
```
Variables
```

?strOriginalName
C:\Users\albiker_e\Documents\Development\uma_p_sql.accdb.src\images\printfast2.ico
?strImageFile
C:\Users\albiker_e\Documents\Development\uma_p_sql.accdb.src\images\printfast.ico
```
Error 53 raised in line
`Name strImageFile As strOriginalName`
...because the sourcefile doesn'exist
![Zwischenablage01](https://user-images.githubusercontent.com/6181166/106207715-7df9ba80-61c2-11eb-983b-23e2411aa6e9.png)

You see in the directory (top right in the picture), that the sourcefile (=strImageFile) has the name "printfast2.png" 
But the file in the original database (left side in the picture) is "printfast2.ico" (exported with V3.2.2)

I think: The error occured in the export of the file "printfast2.ico". Then it was wrongly renamed to "printfast2.png"

Greetings
TanarRi

**Comment by joyfullservice** [comment]
Thank you for the detailed description and screenshots! That really helps in understanding the issue. It is interesting to note that the embedded file's extension does not match the extension column in the recordset. Let me take a look...

**Comment by joyfullservice** [comment]
I just pushed an update to the `dev` branch that I believe will correct this issue. The image file names can be a little tricky because we need to avoid name collisions in the exported source, yet retain the original file names in the rebuilt database. You can apply the change to your current version, or build the `dev` branch from source and use that instead. (Consider the `dev` branch to be the beta version under active development.)

**Comment by Tanarri** [comment]
Thanks! I will it

**Comment by joyfullservice** [comment]
I believe this has been resolved. Let me know if you have any further problems with the image file names!
