### ISSUE TITLE
New Feature: Option to not save "Linked tables"

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#152]
Hi,

in my project (170.000 Lines of code) we have a special feature.
The feature is, that all linked tablenames are in a the local access-db.
At start of the application all linked tablenames a read out of the table "tlktables" and the the linked table is created.

On "export all source" the names and tabledefs of all linked tables are exported. 
Now on my (or some others developer) second computer these tables will be created on "build from source"... but ... the developer has a other name of the ODBC DSN or Database-Server-Name.
--> VCS will fail on creating/importing the linked tabledef.

An option for me ist, to not export/import linked tables
or
if it is possible: only create the tabledef when "building from source"
or
option to ignore the errors on linked errors.

Perhaps you have a better idea

**Comment by joyfullservice** [comment]
@Tanarri - Great question! That is actually the very reason we have the **Run Sub Before Export** [option](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Documentation). This allows you to run some code in your current database just before the source is exported. You could use this to remove all the linked tables, then after the export, you could call another sub to add them back in.

**Comment by Tanarri** [comment]
This is a solution.
I do it so 

Thanks!

**Comment by joyfullservice** [comment]
Closing this out based on the ability to do this with the **Run Sub Before Export** option.
