### ISSUE TITLE
Error 450 on "Build from source"  from file "dbs-properties.json"

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#153]
Hi again,

in my project I use a linked accdb from an other developer (it is a great ListGrid).
For this component a licence key is need and I think it is saved in "dbs-properties.json".

A shortend piece of the file "dbs-properties.json"

```
    "HasOfflineLists": {
      "Value": 70,
      "Type": 3
    },
    "ListGridFC": {
      "Value": [
        234,
        74,
        252,
        30,
        215,
        215,
        94,
        115,
        43,
        29,
        209,
        165,
        162,
        188,
        100,
        104,
        151
      ],
      "Type": 9
    },
    "Name": {
```
I have deleted several lines from the `value` of `ListGridFC` because I think this is a licence key.

The error 450 occurs in procedure "IDbComponent_Import" in class "clsDbProperty":
![Zwischenablage02](https://user-images.githubusercontent.com/6181166/106673432-df020380-65b1-11eb-8e29-6064e5849a37.png)
![Zwischenablage03](https://user-images.githubusercontent.com/6181166/106673434-df9a9a00-65b1-11eb-80f7-75aa8705321e.png)

Sorry @joyfullservice for bringing so much work.
If you need more infos or something don't hesitate to ask

Greetings

**Comment by joyfullservice** [comment]
Type 9 is a binary value (`dbBinary`), which looks like it is being stored as an array of bytes. This will probably require a conversion to get it from the dictionary object to a value that can be restored to the property. Feel free to make some adjustments to `clsDbProperty` and create a pull request when you have something working.  😄

**Comment by joyfullservice** [comment]
This has been merged into `master` and cherry-picked into `dev`. Thanks for your contribution!
