### ISSUE TITLE
close window after "exportallsource" clicked from ribbon

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#157]
After exporting, automatically close the window when clicked from the ribbon; this will make it easier to "go back to work" after exporting.

**Comment by joyfullservice** [comment]
We might also want to verify that there were no errors in the export, and not auto-close if any errors were encountered. (Integrating and checking the global error level in `clsLog.ErrorLevel`)

**Comment by hecon5** [comment]
Added; let me know what you think.

**Comment by joyfullservice** [comment]
Looks good overall. I will add a few comments on the PR...

**Comment by hecon5** [comment]
I think this can close then, with the pr merged.
