### ISSUE TITLE
Improvment: Parse dynamic formatting

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#160]
It would be nice to have ability to parse the dynamic formatting blocks like prtmip.

**Comment by hecon5** [comment]
Note that I have literally no idea how to do this, and internet searches are ... few and far between.

I did find [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3f7ce5d7-9a26-475d-977d-8938df703729/decoding-saveastexts-conditionalformat?forum=accessdev), where the OP was told to pound sand, but nothing else.

**Comment by joyfullservice** [comment]
You might have to reverse engineer it yourself, testing various values and watching what changes in the binary output. It could be pretty complicated with all the different combinations of things involved. My guess is that they might use a structure with flags added together to represent some of the formatting pieces.

It would be pretty cool to see that info parsed out into json, but it will take someone some time and patience to systematically work through figuring out how the data is stored. 😄

**Comment by hecon5** [comment]
I'm going to close this, I don't have anywhere near the time to do this in the near term (or even any term at the moment), but if I figure it out, I'll share it.
