### ISSUE TITLE
Disabling "Aggresive Sanitize" produces invalid form exports

### ISSUE THREAD

**Issue by Ik-12** [joyfullservice/msaccess-vcs-integration#169]
There seems to be a typo/error in logic at line 98 of `modSanitize`. Currently the
block header (e.g. "GUID = Begin") is left out from the exported file which causes syntax
error when trying to import a form. The If-block should probably be as follows:

```
If Options.AggressiveSanitize Then
    blnInsideIgnoredBlock = True
Else
    cData.Add strLine
End If
```

**Comment by hecon5** [comment]
Good catch, I think you're right!

**Comment by joyfullservice** [comment]
The fix has been deployed to the `dev` branch. Thanks again!
