### ISSUE TITLE
After latest dev .json updates, importing tables causes Err 91

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#174]
Error 91 is thrown for every table (linked or otherwise) upon import. Queries seem to import fine.

`ERROR: Build error in: C:\Users\[USER]\Documents\DevelopFolder\Project-Code\Database-Development.accdb.src\tbldefs\dbo_tblStatus.json Source: modImportExport.Build Error 91: Object variable or With block variable not set
`

**Comment by joyfullservice** [comment]
Hmm... Let me take a quick look...

**Comment by joyfullservice** [comment]
Found it. I was incorrectly updating the index. Pushing a fix momentarily...

**Comment by hecon5** [comment]
Zoom! Thanks! My internet died, so I didn't even have a chance after posting this, lol.
