### ISSUE TITLE
Reports Print settings are being discarded. 

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#175]
Report forms are not importing correctly; the page layout is being discarded and resetting to "8x11, portrait" for all reports, regardless of their `JSON` config.

No errors are being thrown (that I see), I've tried several printers as default, and troubleshooting to see what else could be causing it.

**Comment by hecon5** [comment]
I reverted the latest updates to the clsDevMode, and those don't appear to be causing it, either.

**Comment by hecon5** [comment]
More troubleshooting after adding in error logging:
lngReturn returns `-1` fr

```VBA
Public Sub LoadFromPrinter(strPrinter As String)
...Blah blah blah...
        ' Check size of DevMode structure to make sure it fits in our buffer.
        lngReturn = DocumentProperties(0, hPrinter, strPrinter, 0, 0, 0)
        If lngReturn > 0 Then
         '^^ lngReturn is always "-1" for me.

```

**Comment by hecon5** [comment]
I'll make a PR with the logging I added, feel free to commit to it for any fixes you see @joyfullservice.

**Comment by hecon5** [comment]
Adding more logging reveals that before `DocumentProperties(0, hPrinter, strPrinter, 0, 0, 0)` lngReturn is 1. 

This is confounding, because it worked previously, or I thought it did, anyway :(

**Comment by joyfullservice** [comment]
It is working fine for me...

![image](https://user-images.githubusercontent.com/7254992/108605340-2beb2580-7379-11eb-8bb2-f25ae6595a7c.png)

You can do some quick testing with something like the following: 

```vba
Public Sub ShowDefaultPrinterSettings()

    With New clsDevMode
        .LoadFromDefaultPrinter
        Debug.Print ConvertToJson(.GetDictionary, "  ")
    End With

End Sub
```

I know we adjusted one of the printer API calls in #115 but I don't think we did anything with the `DocumentProperties` one.

**Comment by hecon5** [comment]
Returns: 

```VBA
ShowDefaultPrinterSettings
lngReturn: 1
ERROR: WARNING: There has been an error with loading DevMode structure. lngReturn:'-1' Source: clsDevMode.LoadFromPrinter
{
 "Margins": {
  "LeftMargin": 0.25,
  "TopMargin": 0.25,
  "RightMargin": 0.25,
  "BotMargin": 0.25,
  "DataOnly": false,
  "Width": 5,
  "Height": 3,
  "DefaultSize": true,
  "Columns": 1,
  "ColumnSpacing": 0.25,
  "RowSpacing": 0,
  "ItemLayout": "Horizontal Columns",
  "FastPrint": 0,
  "Datasheet": 0
 }
}
```

**Comment by hecon5** [comment]
ugh. I swear this worked like a week ago, too :/

**Comment by hecon5** [comment]
@joyfullservice, what do you get for that? Does it return the page size and orientation for you, or just the margins?

**Comment by joyfullservice** [comment]
I get the paper size as well...

```
{
 "Printer": {
  "Orientation": "Portrait",
  "PaperSize": "Letter"
 },
 "Margins": {
  "LeftMargin": 0.25,
  "TopMargin": 0.25,
  "RightMargin": 0.25,
  "BotMargin": 0.25,
  "DataOnly": false,
  "Width": 5,
  "Height": 3,
  "DefaultSize": true,
  "Columns": 1,
  "ColumnSpacing": 0.25,
  "RowSpacing": 0,
  "ItemLayout": "Horizontal Columns",
  "FastPrint": 0,
  "Datasheet": 0
 }
}
```

**Comment by hecon5** [comment]
hmmmmm; heading in the "right" direction then :/

**Comment by hecon5** [comment]
When I open the report, I can set the orientation and page, and then it exports properly into the `.json`, but it does not then reimport.

**Comment by hecon5** [comment]
Ok, so more troubleshooting: `clsDevMode: LoadFromExportFile(strFile As String)` is never called from build; it looks like it just skips it.

I suspect this has something to do with it:
```VBA
Public Sub ApplySettings(dSettings As Dictionary)

    Dim intCnt As Integer
    Dim strForm As String
    Dim bteForm() As Byte
    Dim varKey As Variant
    Dim blnSetDevMode As Boolean
    Dim dItems As Dictionary
    Dim strPrinter As String
    
    ' Set the properties in the DevNames structure.
    ' Note that this simply sets the printer to one with a matching name. It doesn't try to reconstruct
    ' an identical share and port name or install a missing printer.
    strPrinter = dNZ(dSettings, "Device\DeviceName")
    If strPrinter = vbNullString Then
        ' Use default printer
        LoadFromDefaultPrinter
        ' Clear the device name, since we are not binding this
        ' form/report to a specific printer.
        For intCnt = 1 To 32
            m_tDevMode.strDeviceName(intCnt) = 0
        Next intCnt
    Else
        ' Load defaults from specific printer
        LoadFromPrinter strPrinter `<<< This line here seems to ensure that the .json file is ignored...
    End If


```

**Comment by hecon5** [comment]
This routine looks like it's actually just totally ignoring the `.json` file (well, not totally, as it does check to see if there is one first, as the `ApplySettings` from above never actually uses the file info. But the `ApplySettings` doesn't ever actually use the `.json` data or settings. 


```VBA
Public Sub LoadComponentFromText(intType As AcObjectType, _
                                strName As String, _
                                strFile As String, _
                                Optional cDbObjectClass As IDbComponent = Nothing)

    Dim strTempFile As String
    Dim strPrintSettingsFile As String
    Dim strSourceFile As String
    Dim blnConvert As Boolean
    Dim dFile As Dictionary
    
    ' The path to the source file may change if we add print settings.
    strSourceFile = strFile
    
    ' Add DevMode structures back into forms/reports
    Select Case intType
        Case acForm, acReport
            'Insert print settings (if needed)
            If Not (cDbObjectClass Is Nothing) Then
                With New clsDevMode
                    ' Manually build the print settings file path since we don't have
                    ' a database object we can use with the clsDevMode.GetPrintSettingsFileName
                    strPrintSettingsFile = cDbObjectClass.BaseFolder & GetSafeFileName(strName) & ".json"
                    Set dFile = ReadJsonFile(strPrintSettingsFile)
                    ' Check to ensure dictionary was loaded
                    If Not (dFile Is Nothing) Then
                    ' Insert DevMode structures into file before importing.
                        ' Load default printer settings, then overlay
                        ' settings saved with report.
                        .ApplySettings dFile("Items")
                        ' Insert the settings into a combined export file.
                        strSourceFile = .AddToExportFile(strFile)
                    End If
                End With
            End If
    End Select

```

**Comment by hecon5** [comment]
SUCCESS! Declarations are muurrrrder. 

I updated the calling declarations; it turns out that if you don't declare `phPrinter As LongPtr`, then it will not work, but it won't say it wont' work. 

This might be a case where we may need conditional compiling, if non-64bitversions don't like `lngptr`.

I'll be updating the PR with some cleaned up code momentarily.

**Comment by joyfullservice** [comment]
This works great on my side. I also added a couple tests in 6b73cae so we can have this automatically verified going forward. (Feel free to add objects and tests to the Testing.accdb file, which you can also build from source. This gives us a simple implementation of automated testing that helps us verify that changes we make today don't break something we fixed yesterday.  😄)
