### ISSUE TITLE
Propose merge Dev onto master and update release to new build 3.3.0

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#177]
Propose updating master with changes from dev, updating the release, and updating the build. 

I also propose updating the release build to 3.3.0, and the develop release to 3.3.(build); which would be updated with each new PR. upon a new PR, the last (or perhaps it would be better to do when you make a new branch?) action would be to increase the build number via `IncrementAppVersion` and `Deploy`.

This would be a new process, but would help differentiate between test builds when doing PR testing. This would help to ensure the the version you're running tests on is either the current "dev" branch version or the one you're reviewing by the build number, instead of compiling the wrong one, switching branches, and forgetting you haven't compiled it yet (something I've done, and I think was a contributor to the recent need to re-fix the clsDevMode again).

**Comment by joyfullservice** [comment]
Sounds like a good approach to me. I am getting ready to release 3.3.0 on `master` this morning, and `dev` can become 3.3.1. When we merge `dev` into master for general releases, we can carry over the existing build number. (For example, the next `master` release might be 3.3.14 or whatever the current build number happened to be.)

**Comment by hecon5** [comment]
Yep! That's exactly what I was thinking for versioning!

**Comment by hecon5** [comment]
Looks like this is done; closing now.
