### ISSUE TITLE
Refactor "integer" types to "long"

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#178]
Slog:
Refactor `integer` types to `long` types, as with the current versions of VBA, `integer` uses the same memory space as `long`, but does not get the advantages of a `long` data type. 

See [StackOverflow: Why Use Integer Instead of Long?](https://stackoverflow.com/questions/26409117/why-use-integer-instead-of-long)

**Comment by hecon5** [comment]
@joyfullservice; this probably should go to a discussion, as it's an over-arching concept, and might not affect anything, but could inform new development work ongoing.
(Putting this on the right issue this time........)

**Comment by joyfullservice** [comment]
Perhaps we should make a page in the wiki where we describe the coding conventions and practices used in this project. Specific discussions like this could be added as discussion questions, and the wiki page updated per the outcome of the discussion.

Just so you know where I am at with some of these things, generally, I would lean towards the best practices promoted by RubberDuck VBA, with a few exceptions based on the purpose and target audience of this project.

**Comment by hecon5** [comment]
I agree with this; RD's coders are waaay more experienced and hooked into the current standards than I am, and also have the energy to build an auditor, so, I agree.
