### ISSUE TITLE
Remove UIDs from connection strings that use `Trusted_Connection=Yes`

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#181]
The user ID (UID) will change when source is exported by different users, but is not really needed when using a trusted connection. I think the add-in should strip out the UID value when it finds `Trusted_Connection=Yes`. This will help reduce source changes when multiple users are working on the same project.

`"Connect": "ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;`**UID=johndoe;**`Trusted_Connection=Yes;APP=Microsoft Office 2010;DATABASE=MySQLDatabase"`

This should be pretty easy to do with linked tables, and slightly more difficult with pass-through queries because the connection string line will need to be parsed and reconstructed.

**Comment by hecon5** [comment]
I agree. I have a function I use to switch from test to production that could probably be used. I won't be able to get to this until Monday right now unfortunately.

**Comment by hecon5** [comment]
Looked up regex call (this probably needs re-written, but it works, and there are other things that need rewritten and don't, soooo). Th rest of the routine to re-target the tables will need more redaction as it's pretty tied to my environment at the moment, but this was the hard part from what I remember developing this portion a while back.

I also have a note in my code to look at [StackOverflow: Regex VBA](https://stackoverflow.com/questions/21264100/regex-vba-in-access-finding-text-between-two-strings), in case that's helpful in the interim.

Should be able to get the UID by changing `SERVER=" to `UID=` and returning everything but the match (I can't remember what the regex replace is for that.

You will also need to reference in `Microsoft VBScript Regular Expressions 5.5` (I think that's the latest?).

```VBA
Function FindODBC_Server(ByVal sourcestring As String) As String

    Dim objRE As New RegExp
    Dim Wynik As Variant
'wynik is used here instead of the function return string to allow shorter debugging (for now) But honestly
'you're probably NEEEEVer ever going to change this, so this note
'will sit in perpetuity.

'this has been written to grab a connection string, return the server ID/name, and return it
    With objRE
        .Global = True
        .ignorecase = True
        .pattern = "(.*)(SERVER=)([^; \r\n]*)(;?.*)"
        Wynik = .replace(sourcestring, "$3")   'only 2nd part of the pattern will be returned

    End With
FindODBC_Server = Wynik
 '   MsgBox (Wynik)
    
    Debug.Print Wynik

End Function
```

**Comment by hecon5** [comment]
Try this out: 

`.pattern ="(.*)(UID=)([^; \r\n]*)(;)(;?.*)"`
`.replace(sourcestring, "$1$5")`

Should return the stripped out UID; testing to ensure `TrustedConnect=True` still working on that.

**Comment by joyfullservice** [comment]
Okay, I have an update that I have tested on both the testing database, and another database with linked SQL server tables. Looks like it is working great on both export and import. (Note that the UID values are automatically recreated on import, but that shouldn't be a problem since they are stripped out on export.)

**Comment by joyfullservice** [comment]
RegEx is cool! I ended up taking a bit simpler approach that I hope is easier to read and maintain in the long run, especially since we have at least three different things we are modifying/adjusting in the connection string. Basically I just split the connection string by the semi-colon delimiters, and rebuilt the string piece by piece, making any necessary adjustments to the parts individually.

```vba
'---------------------------------------------------------------------------------------
' Procedure : SanitizeConnectionString
' Author    : Adam Waller
' Date      : 2/26/2021
' Purpose   : Sanitize the connection string by removing unneeded information and
'           : converting database path to relative.
'---------------------------------------------------------------------------------------
'
Private Function SanitizeConnectionString(strConnection As String) As String

    Dim lngPart As Long
    Dim varParts As Variant
    Dim strPart As String
    
    If strConnection = vbNullString Then Exit Function
    
    ' Create array of connection string parts
    varParts = Split(strConnection, ";")

    ' Loop through parts, building new connection string
    With New clsConcat
        .AppendOnAdd = ";"
        For lngPart = 0 To UBound(varParts)
            strPart = CStr(varParts(lngPart))
            Select Case True
                
                ' Check for username/password
                Case StartsWith(strPart, "UID=", vbTextCompare), _
                    StartsWith(strPart, "PWD=", vbTextCompare)
                    ' These values are not needed when using a trusted connection.
                    If InStr(1, strConnection, "Trusted_Connection=True", vbTextCompare) = 0 _
                        Or Not Options.AggressiveSanitize Then
                        ' Retain the values if not using trusted connection, or if
                        ' AggressiveSanitize option is set to false (Defaults to true).
                        .Add strPart
                    End If
                
                ' Check database path to convert to relative
                Case StartsWith(strPart, "DATABASE=", vbTextCompare)
                    .Add GetRelativeConnect(strPart)
                
                ' Add all other sections
                Case Else
                    .Add strPart
            End Select
        Next lngPart
        
        ' Remove trailing semicolon, and return string
        .Remove 1
        SanitizeConnectionString = .GetStr
    End With
    
End Function
```

**Comment by hecon5** [comment]
Figured it out! Try this: [Strip out UID if Trusted Connection is found](https://www.regextester.com/94017)

`(.*)((;UID=)(?=[^ \r\n]*;Trusted_Connection=Yes))([^; \r\n]*)(;?.*)` will match

**Comment by hecon5** [comment]
`(.*)(;UID=[^ \r\n]*)(?=;Trusted_Connection=Yes)|(;PWD=[^ \r\n]*)(?=;Trusted_Connection=Yes)([^; \r\n]*)(;?.*)` Should get both of the PWD and UID if trusted connection is found.

Return `$1`will return the stripped string.

**Comment by hecon5** [comment]
Ok, last one:

`(.*)(((;UID=)|(;PWD=))[^ \r\n]*(?=;Trusted_Connection=Yes))`
`.replace(sourcestring, "$1")` 

Should strip out PWD and UID if it's trusted, and ignore it if not. 


```REGEX
ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;UID=johndoe;Trusted_Connection=Yes;APP=Microsoft Office 2010;DATABASE=MySQLDatabase

ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;UID=johndoe;PWD="WFEFE";APP=Microsoft Office 2010;DATABASE=MySQLDatabase

ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;UID=johndoe;Trusted_Connection=Yes;APP=Microsoft Office 2010;DATABASE=MySQLDatabase

```

Returns: (with $1 as the substitution rule)
```
ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;Trusted_Connection=Yes;APP=Microsoft Office 2010;DATABASE=MySQLDatabase

ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;UID=johndoe;PWD="WFEFE";APP=Microsoft Office 2010;DATABASE=MySQLDatabase

ODBC;Description=MyProgram;DRIVER=SQL Server;SERVER=DbServer;Trusted_Connection=Yes;APP=Microsoft Office 2010;DATABASE=MySQLDatabase
```

**Comment by hecon5** [comment]
I'm sorry, I can't help myself; this one should cut down on memory use as it only requires a pointer and directly edits the string in place.

```VBA
Private Sub SanitizeConnection(ByRef SourceString As String)

    Dim objRE As New RegExp
    Dim ReturnString As Variant

'this has been written to grab a connection string, return the sanitized string.

    With objRE
        .Global = True
        .ignorecase = True
        .pattern = "(.*)(;UID=)[^ \r\n]*(?=;Trusted_Connection=Yes)|(;PWD=)[^ \r\n]*(?=;Trusted_Connection=Yes)"
        sourcestring = .replace(sourcestring, "$1")   'Return the sanitized string.

    End With
End Sub
```
