### ISSUE TITLE
clsConcat: Error if GetStr ist a multiple of 4096

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#194]
I had exported my big project several times with no problem, but today I got one with version 3.3.13
Please turn on debugging mode in VCS, otherwise the error will be not shown

With a additional debugging tool (vbWatchdog https://www.everythingaccess.com/vbwatchdog.asp ) I tracked it down to following line of code in clsConcat which fail:
Mid$(GetStr, (lngCnt * clngPageSize) + 1, clngPageSize) = astrPages(lngCnt)

The variables contents are on start of the procedure:
The string "GetStr" will be initialised with length 53248
![grafik](https://user-images.githubusercontent.com/6181166/110864382-510ced00-82c2-11eb-9405-deeca70736b4.png)

And in the 13th interation:
A assignment will performed on position 53249 (1 past the end of initial string "GetStr") which results in Error 5

?Err.number, Err.Description
 5            Ungültiger Prozeduraufruf oder ungültiges Argument (Propagate to 'MSAccessVCS.modVCSUtility.SaveComponentAsText')

![grafik](https://user-images.githubusercontent.com/6181166/110865139-6b939600-82c3-11eb-9ae6-a00405c90abf.png)

The error is skipped when debugging is turned off, but should still be fixed.

**Comment by joyfullservice** [comment]
Thanks for reporting this! I have just pushed an update that should resolve this issue. Let me know if you encounter any further problems with the concatenation class.

**Comment by joyfullservice** [comment]
Sounds like we still have a little more to do on this, as noted in #195. I will try to look at this on Monday, unless someone else wants to offer a pull request before then.

**Comment by joyfullservice** [comment]
Thanks for the PR! It appears to have solved the issue, so I will go ahead and close this out. Feel free to reopen if anything further comes up. 👍
