### ISSUE TITLE
Upgrading from 3.1.x does not remove old version.

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#204]
See joyfullservice#203: 
_Originally posted by @cameo69 in https://github.com/joyfullservice/msaccess-vcs-integration/discussions/203_

The installer does not remove prior versions for pre-3.3.x versions. I suspect this may be related to, but not caused by changing the Addin Links in joyfullservice#158.

**Comment by hecon5** [comment]
@cameo69: one more question, when you opened the old version, did it open the new file, or the old one?

I suspect two things are happening here: 
The old menu item is / was linked to the prior file, and the new menu items are pointing to the file that has its own folder (as the addin was moved to its own VCS folder in bc0a522. 

The installer doesn't (or can't?) check the other file location due to permissions (or it forgot); this leaves the old file there.

**Comment by joyfullservice** [comment]
I was able to reproduce the issue on my computer, and pushed an update to the `dev` branch. After this gets pushed out to `master`, you should be able to remove the legacy version by doing the following:

1. Install version 3.1.56
2. Install version 3.3.1

At that point you should only see the current menu items.

We are getting close to releasing another update to the `master` branch, but if you want to fix it now, you can check out the project and build the `dev` branch from source, and open `Version Control.accda` to install the latest dev version.
