### ISSUE TITLE
Automation error

### ISSUE THREAD

**Issue by gbrandt** [joyfullservice/msaccess-vcs-integration#212]
I am getting the following error on import and don't know why:

-------------------------------------
Beginning Build from Source
Job Orders.accdb
VCS Version 3.3.17
2021-04-21 1:19:58 PM
-------------------------------------
Saving backup of original database...
Saved as Job Orders_VCSBackup.accdb.
Created blank database for import.
-------------------------------------
Removing non built-in references...
  Removed DAO
  Removed stdole
-------------------------------------
No themes source files found.
-------------------------------------
Importing vb project...       
  vbe-project.json
ERROR: Importing VBE Project Source: clsDbVbeProject.Import Error -1905920032: Automation error
[1]
-------------------------------------
Importing vbe references...   
  vbe-references.json
[1]
-------------------------------------
No vbe forms source files found.
-------------------------------------
No proj properties source files found.
-------------------------------------
No saved specs source files found.
-------------------------------------

**Comment by hecon5** [comment]
Can you go into the `vbe-project.json` file and tell us what the `helpfile`, `helpcontextid`, `conditionalcompilationarguments`, `mode` are?

**Comment by joyfullservice** [comment]
@gbrandt - It sounds like you are probably experiencing #197. This has been resolved in later builds. I am attaching the latest dev build. Can you try installing that and see if that resolves the issue for you?
[Version Control_v3.3.26.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/6353135/Version.Control_v3.3.26.zip)

**Comment by gbrandt** [comment]
{
  "Info": {
    "Class": "clsDbVbeProject",
    "Description": "VBE Project"
  },
  "Items": {
    "Name": "Sales Orders",
    "Description": "",
    "FileName": "rel:Job Orders.accdb",
    "HelpFile": "111256772",
    "HelpContextId": 0,
    "Mode": 0,
    "Protection": 0,
    "Type": 100
  }
}

**Comment by gbrandt** [comment]
> @gbrandt - It sounds like you are probably experiencing #197. This has been resolved in later builds. I am attaching the latest dev build. Can you try installing that and see if that resolves the issue for you?
> [Version Control_v3.3.26.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/6353135/Version.Control_v3.3.26.zip)

The error no longer appears with the dev build.  Is the dev build safe to use in production?

**Comment by gbrandt** [comment]
And more importantly, was there any data loss with the error?

**Comment by hecon5** [comment]
You could also change the lines:

```JSON 
"HelpFile": "111256772",
"HelpContextId": 0,

```

to 
```JSON
"HelpFile": "",
"HelpContextId": ,
```

And then it'll work.

**Comment by gbrandt** [comment]
Got it, but the help is regenerated on every export I think.  thanks for the help

**Comment by hecon5** [comment]
It's actually regenerated upon "import"; because it's in your Project already, every time you export it is still persistent. It's used by RubberDuckVBA to track a VBAIDE instance, so it'll keep showing up.
For right this second, ignoring it is the best case; it's code noise, though they are looking at getting rid of it.

Actually: when you say "regenerated" do you mean with the **new version** is still exporting a `HelpFile` value?

**Comment by gbrandt** [comment]
> It's actually regenerated upon "import"; because it's in your Project already, every time you export it is still persistent. It's used by RubberDuckVBA to track a VBAIDE instance, so it'll keep showing up.
> For right this second, ignoring it is the best case; it's code noise, though they are looking at getting rid of it.
> 
> Actually: when you say "regenerated" do you mean with the **new version** is still exporting a `HelpFile` value?

The dev version does not appear to fill in this field on export.   An import/export/import cycle does not fill the field either.  Thanks again.

**Comment by joyfullservice** [comment]
> 
> The error no longer appears with the dev build. Is the dev build safe to use in production?

At the present time the `dev` branch is just ahead of the `master` and I periodically summarize the changes in a release on the `master` branch. There have been seasons where the `dev` branch took a longer deviation from `master` when a major refactoring was in process, but right now it is just bug fixes and minor features that we are working on.

As for whether it is safe to use in production, you can review the commit history in git to see what has changed, but I personally feel it should be as safe as the `master` branch for this version 3.3.26. (And includes some bug fixes as you observed here.)

Of course this goes without saying that it is ultimately up to you as the developer to test, review, and assess whether it is ready for production use in your environment. (Just like with any open-source software)  😄

If you are interested, you can also clone this project and build from source (using this add-in) to incorporate all the latest commits between general releases. That's what several of us do that use this add-in on a more daily basis. Being able to build form source makes all the difference in being able to easily build this add-in (or other projects) from different branches. After building the add-in from source, you just double-click the file to install that version.

Hope that helps!
