### ISSUE TITLE
"Build from source" fails if export folder was a subdiretory

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#214]
Hi,

I exported a accdb named "test.accdb" to subdirectory "\tools\%dbname%.src" - this was all right.
The export files are in the subdirectory "\tools\test.accdb.src" of the original database .

Then I want to "build from source" this database. Steps:
- Open the original database "test.accdb" and start VCS
- choose "build from source"
- Select "YES" from the messagebox. In this message box the right folder for import was shown: D:\<snipedPath>\tools\test.accdb.src\"
- The procedure "build from path" reported success, but no objects were imported. A empty accdb was generated.

Infos:
The generated empty database is saved here: "\tools\test.accdb". I thought it wil be generated in path "\test.accdb"
A directory "\tools\tools\test.accdb.src" was created with the files "Build.log" and "vcs-index.json" (Build.log enclosed)

Gretings
TanarRi

[Build.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/6373131/Build.log)

**Comment by joyfullservice** [comment]
I was able to reproduce this error. Looks like an issue with handling the export path... Let me see if I can resolve this...

**Comment by joyfullservice** [comment]
@Tanarri - I believe this should be resolved now. Can you verify that it works on your system?

**Comment by Tanarri** [comment]
@joyfullservice 
Yes, the fix works on my system.

Great work - Thanks!
