### ISSUE TITLE
Getting Error during build 

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#226]
I'm getting an intermittent unhandled error during build from Vb project; I think it's related to the helpfile parsing. If I step through the first part of the build, it works fine; if not, I get an unhandled exception "somewhere". Trying to figure out more.

Excerpted Log: 

-------------------------------------
Beginning Build from Source
[Redacted]
VCS Version 3.3.35
5/20/2021 12:12:53 PM
-------------------------------------
-------------------------------------
Importing vb project...       
  vbe-project.json

-------------------------------------
ERROR: Unhandled error found before `On Error` directive
-------------------------------------
Error 440: Automation error Source: Unknown
[1] vb project processed.

**Comment by hecon5** [comment]
Still attempting to troubleshoot this; I think it happens around the location of the `SafeSetProperty`. If I step through at least the VBE-Project, it will import just fine.

**Comment by hecon5** [comment]
Added `    CatchAny eelError, "Setting Property:" & strProperty & ", Value:" & CStr(varValue), ModuleName & ".SafeSetProperty"
` to `SafeSetProperty` at the end; and with the testing database it reveals that some values are throwing errors.

**Comment by hecon5** [comment]
If for some reason help context ID was a non-zero number, it'll pass muster, but I still cannot set it in my environment. Clearing the error helps, and debugs it, but it won't set (for me).
```
-------------------------------------
ERROR: Setting Property:HelpContextId, Value:123456
-------------------------------------
Error 440: Automation error Source: clsDbVbeProject.SafeSetProperty
```

**Comment by joyfullservice** [comment]
@hecon5 - I made some additional changes to the VBE property import functions. Can you verify that this still works correctly for you?

**Comment by hecon5** [comment]
This appears to function; I haven't been getting the error, but I'll keep my eye on it.

**Comment by hecon5** [comment]
So, I'm getting this error again with the latest 3.4.11; it does work, however (eg, I get an error and I shouldn't be, because the value is set correctly).

**Comment by joyfullservice** [comment]
Where are we at on this one? It looks like it is currently the last issue tied to the 3.4.x milestone... Is this something that could be easily reproducible?

**Comment by hecon5** [comment]
I get it intermittently on the testing database. The error itself is a false positive; it definitely sets the value, just throws an error also (at least...seems to).

**Comment by hecon5** [comment]
To be clear; I think this should be bumped to the next version. It's a nuisance, but doesn't break anything.

**Comment by joyfullservice** [comment]
Taking a look at the code again, it looks like this was a simple logic error. If the property is successfully set, any corresponding error should be discarded before reaching the final error handler. (As long as the value was correctly set, we are not too concerned about an error thrown in the process.)
