### ISSUE TITLE
Large no of Files are Being Created after Compiling the Project

### ISSUE THREAD

**Issue by abdullah1038** [joyfullservice/msaccess-vcs-integration#227]
Hello,

I don't know it's with me or anyone notices too, large no of files are being created even if a single file is changed after compiling (Debig>>Compile). Is there a way to get only those files which are actually modified?

Best Regards
Abdullah

**Comment by hecon5** [comment]
Hi, do you mean they're created after you export? 

The VCS will export all modified files from the Access Database. Oftentimes, if you do "Debug/Compile" (or especially if you do "Compact>Repair"), the VBA IDE will "helpfully" recapitalize routine, function names, variables, etc. 

Additionally, if you have Access 2013+, when you export forms the colors may change (apparently randomly) from export to export. This is partially due to how Access's internals are handling it, partially due to your OS's color settings, and how they interact with each-other. 

It's a really annoying ~~bug~~ "feature, and one that plagues me, too.

**Comment by abdullah1038** [comment]
Thanks for reply. Yeah differences show only colors changed and also
left/top or height width changes. So, I guess there is no way to get rid of
this feature.

Regards

**Comment by hecon5** [comment]
There is...if you don't open them between exports. But...that's impractical, obviously.

I've been trying to figure out how to eliminate those changes, especially for forms that are dynamically colored/adjusted/generated where the "base" color makes no difference (or where I've used a theme to define the color), but I'm coming up short.

I was thinking of adding an RD flag, and adding a specialized sanitize routine to "revert" color changes, but I've got so much other stuff on my plate right now, it's just a theory banging around in my head at the moment.

**Comment by hecon5** [comment]
Since there's nothing we can do about this irritation for now except interrupt the IDE which is far outside the scope of the Addin's purpose, I'd suggest putting this under "Access Bug/Can'tFix".

**Comment by abdullah1038** [comment]
Yeah sure. Put it under Access Bugs /Can't solve. I was thinking that there
is something that I might be doing wrong so it is now clear.

Thanks and regards.
Abdullah

**Comment by hecon5** [comment]
You're doing it correctly; I, too, wish this wasn't how it worked :/

**Comment by abdullah1038** [comment]
You said if I don't open then between exports then these will not be
generated but for me these are. I did export and then imported a module
into my project from another project and then use debug/compile and then
exported again, there were 93 files (including one newly added module).

**Comment by hecon5** [comment]
Can you attach a screenshot of what's changing? Perhaps we're discussing different nuances?

An example of what I'm talking about on a form:
![image](https://user-images.githubusercontent.com/54177882/119155264-fcec5a80-ba20-11eb-9881-90509e55c2fb.png)

**Comment by abdullah1038** [comment]
These are images from 10 different forms. Please notice, some command is
deleted and the same is added again.

**Comment by abdullah1038** [comment]
![1](https://user-images.githubusercontent.com/79572473/119169964-0e168500-ba7c-11eb-97cb-6f078fa38505.jpg)
![10](https://user-images.githubusercontent.com/79572473/119169977-1078df00-ba7c-11eb-939e-2b7c31bda3b3.jpg)
![2](https://user-images.githubusercontent.com/79572473/119169980-11117580-ba7c-11eb-8fa0-d6ebd8d4ceb0.jpg)
![3](https://user-images.githubusercontent.com/79572473/119169983-11aa0c00-ba7c-11eb-9868-94ee6e2fea13.jpg)
![4](https://user-images.githubusercontent.com/79572473/119169985-1242a280-ba7c-11eb-950d-22be7a817aa2.jpg)
![5](https://user-images.githubusercontent.com/79572473/119169987-12db3900-ba7c-11eb-85dc-021a6da55fd2.jpg)
![6](https://user-images.githubusercontent.com/79572473/119169988-140c6600-ba7c-11eb-8953-f760fb40f615.jpg)
![7](https://user-images.githubusercontent.com/79572473/119169991-153d9300-ba7c-11eb-82e8-b2981d440d8d.jpg)
![8](https://user-images.githubusercontent.com/79572473/119169994-15d62980-ba7c-11eb-83a6-39b19c74b5fc.jpg)
![9](https://user-images.githubusercontent.com/79572473/119170001-166ec000-ba7c-11eb-9997-474624f6e18b.jpg)

**Comment by hecon5** [comment]
yup, those are VBA's IDE "help". 

There's nothing to do about that, they'll change at random, sometimes they'll stay the same for a while and then strike when you least expect it. Think of it as Monty Python's "Spanish Inquisition": they're fools, they show up randomly, they are definitely not helping you, but they're not "hurting" you either ("NOT THE COMFY CHAIR!").

It's likely you never noticed this before you had a decent VCS (I didn't), but I started noticing it as soon as I started using git and diff tools (several years now, and consistent across all VCS's I've used (hand-built one, the "legacy" version of this Addin, and the addin now).

**Comment by abdullah1038** [comment]
So nice of you. I had been seeing these from start but lately they
increased in number so I asked. Thanks a lot.

**Comment by joyfullservice** [comment]
For more discussion on changes in color values, see #183 
I have recently added a [FAQ page](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/FAQs) to the project wiki where some of the other reasons are outlined.

I will go ahead and close this issue out, since the underlying issues are documented elsewhere. Thank you all for the input! 😄
