### ISSUE TITLE
Throws errors on 64-bit Office

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#23]
This is due to new DLL declare statement without PtrSafe flag.

**Comment by joyfullservice** [comment]
@A9G-Data-Droid - As of today's code, I don't see any declares without the PtrSafe flag... Let me know if you are still seeing this issue in the latest version.

**Comment by A9G-Data-Droid** [comment]
Yup, I'm using your master that was updated 14 minutes ago. I am working on a patch but I can't export my patch as the addin isn't registering for me.

**Comment by joyfullservice** [comment]
You should be able to open the database, make your changes, and then run `Deploy` from the immediate window... That will export the source code, and update your installed version of the add-in in one step.
