### ISSUE TITLE
Release 3.4.0 Steps

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#234]
Release 3.4.0 issue discussion, see my thoughts below; written in semi-template fashion to be able to reuse for future releases.

# Significant Changes / Bug Fixes

- #197 Help Context Error
- #210 Git Hidden (for now)
- #214 Build Fails if subdirectory
- #217 Non-ASCII Character fix
- #218 Save as Default fix
- #230 Class / Module Attributes saved **Update: No longer breaking change**

# Issues we need to close prior to release:
These issues should be closed prior to the release (eg, bugs stem from other issue fixes and can be fixed, features that need to be repaired, or cleanup needed).

- None

# Cleanup needed prior to release:
Code tidying, cruft removal, etc. that needs to ensure the release code is 'tidy'.

- Done (@joyfullservice removed these yesterday).

# Bug Issues not in release scope:
Issues that are known, but are too complex to fix under this release, or have been endemic to Addin and are not degradation of feature sets, or are currently out of scope / planned for the future. 
Issue|Description|Disposition & Reason for exclusion
- #227 (VBA IDE, CANTFIX) **can probably close this one.**
- #226 Error during build (still in troubleshooting, does not appear to affect built dB).
- #229 Show animation during build (does not affect built db)

# Feature Issues not in release scope:
- #34 Add ribbon controls (New feature, may be possible with TwinBasic)
- #87 Translation Support (In development, not ready)
- #107 Disable Auto-Backup (option, new feature, does not affect build)
- #118 Auto-Update (new feature, not slated for dev yet).
- #185 Sanitize Queries (new feature, does not affect dB)
- #222 Support RubberDuck @ folder (new feature, future possibility)
- #224 Select dB Build version (New feature, planning stages)

# Any other release caveats:
Items we need to consider prior to release.

[Edit]: below is no longer correct, it's been addressed, can still import from prior db versions.
- This is a breaking release (#230 Module export now includes hidden Attributes that were previously not shown). Export of modules from 3.4.0 won't be build-able by prior versions. Also, it appears as though importing legacy exported classes does not import as class without proper header information. Perhaps there's a way to alternate if the header is not found, but that might be a performance hit.

**Comment by joyfullservice** [comment]
Thanks for putting this together! I wonder if milestones might be a good fit for this... We could then assign the relevant issues to the milestone, and include some of the notes in the milestone description.

**Comment by hecon5** [comment]
We use Jira for our feature/issue tracking, and use their release version to track this, and it makes it a breeze to track what's happening version to version. It's a combination of Issue Tracking, GitHub Projects, milestones (if I understand correctly, GitHub Milestones ~= Releases in Jira). 

The thing I really like is that it automatically moves tickets along, so you can see what's integrated to stable, still in beta ('dev' in this case), being worked on, troubleshooting stages, etc. And as an issue gets moved along, it closes/changes state. Also makes creating a release log as easy as remembering to tag your commits; click "See Issue notes" and it's done. 

Anyway, that's a long-winded way to say "I like it, and I'm all for automating mundane tasks out of needing to be done".

**Comment by A9G-Data-Droid** [comment]
Generally, the major version number is used to indicate breaking change. So we would roll to version 4.0 so you can explain that this version is not compatible with previous versions.

**Comment by hecon5** [comment]
Update: no longer a breaking change, updated above.

**Comment by hecon5** [comment]
Ready for launch?

**Comment by joyfullservice** [comment]
I think we are ready for launch!  🚀  I will see if I can get the release notes put together and push this out today!

**Comment by hecon5** [comment]
Closing, released!

**Comment by Indigo744** [comment]
I just want to take the time to say thank you 😸 Really thank you all for the tremendous amount of work you are all doing on this!
