### ISSUE TITLE
Partial object definition blocks in source cause colors to be lost on rebuild

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#235]
In #183 we worked through an approach to sanitizing out dynamic theme color values that can change between builds, and are not needed to represent the actual color of the control. However, this uncovered another issue where in certain situation, such as when a database is migrated from prior versions of Microsoft Access, the property definition block in the source code file is incomplete. Specifically, it may have a color value, but does not have the `ThemeColorIndex` line that tells us whether the color is an absolute color, or a theme-based color.

To resolve this problem, existing color properties need to have the existing color applied through VBA to ensure that the color value is stored correctly, and able to export will all the necessary lines used to determine whether the color value should be sanitized from the source file.

**Comment by hecon5** [comment]
I'm now seeing some pretty serious theme issues from #183. Controls are all being reset to white or black. Themese are ignored. 

Header backgrounds and *some* detail rows are remaining.

**Comment by hecon5** [comment]
Is this fixed with the sanitize option?

**Comment by joyfullservice** [comment]
Yes, this seems to be resolved as far as I can tell. I will go ahead and close it out unless we hear otherwise.
