### ISSUE TITLE
Add Sanitize levels to sanitize

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#239]
Instead of the current "all or nothing for aggressive sanitize" options for sanitization, I think it would be good to implement levels.

Would allow users to see "raw" file exports, and us to introduce new cleanups that may produce unexpected results in larger dbs without needing to keep switching addin versions. 

If there's interest, I can roll these into the pr #238 I made, and we can give those a go.

**Comment by hecon5** [comment]
If `AggressiveSanitize = False` then the Sanitize level is set to `eslBasic`;if true then `eslAggressive`. 

Also added in beta mode, and a property to allow use of the legacy `aggressiveSanitize` property that acts the same as it used to.

This removes the `AggressiveSanitize` option from `vcs-options.json` once it's been converted to the level. 

# Screens: 
### (`AggressiveSanitize = False`)
![image](https://user-images.githubusercontent.com/54177882/122263529-8cf8b500-cea4-11eb-8f97-8ec9e4b59869.png)

### (`AggressiveSanitize = True`)
![image](https://user-images.githubusercontent.com/54177882/122263795-d3e6aa80-cea4-11eb-9beb-2696e8379bc0.png)

**Comment by hecon5** [comment]
Also, if somehow `SanitizeLevel` is set (or present) in the options and so is `AggressiveSanitize` in `vcs-options.json` then `SanitizeLevel` will be used as the level, regardless of `AggressiveSanitize` setting. Next time the options are saved, `SanitizeLevel` will stay and `AggressiveSanitize` will be removed.

Also updated the control widths a bit; they look better now, even with the Beta option set.

![image](https://user-images.githubusercontent.com/54177882/122268453-152d8900-ceaa-11eb-8caa-3b49ba7af001.png)

**Comment by hecon5** [comment]
FWIW: I think users should know that there may be/are issues with the upper most level, which is why I added "BETA" to the end. I also wanted it to be consistent between color / general sanitization, especially if we start adding in more features in the sanitization routines.

**Comment by joyfullservice** [comment]
Nice work! I like the combo boxes for setting the sanitize levels. 👍

**Comment by hecon5** [comment]
Just occured to me that updating the wiki pages would be good here. I'll get those tidied up, too.

**Comment by joyfullservice** [comment]
> 
> 
> Just occured to me that updating the wiki pages would be good here. I'll get those tidied up, too.

Awesome! You will see the subfolder for images, so if you can put the screenshots there, name and link them accordingly, that would be perfect!

**Comment by joyfullservice** [comment]
This has been merged into `dev` on #241. Thanks, @hecon5 for the great work!

**Comment by A9G-Data-Droid** [comment]
I finally got around to testing and I don't see the new sanitize levels. I pulled down from `dev`, Built the addin from source, then installed the latest one. Did this get removed from dev later?

It doesn't help that the version has been 3.4.1 for a long time. We need some dynamic build like `3.4.1.20210625` so it's easy to tell at a glance what build you are using. Currently, we can't see which build of 3.4.1 someone is using.

**Comment by joyfullservice** [comment]
A fresh build from the `dev` branch should build `3.4.5`... Maybe double-check that the branch has the latest commit de687b0
 from June 17th, and that after closing all Access windows, run the newly built file to install version `3.4.5`. Let me know if this works!

**Comment by joyfullservice** [comment]
Also note that @hecon5 has reported issue #236 relating to the saving of code modules after importing through VBE. I haven't really experienced that in my testing, but I wanted to mention it in case you see anything similar with your system.

**Comment by A9G-Data-Droid** [comment]
Thanks, it was operator error. I got the `3.4.5` now. I am testing the aggressive color sanitize.
