### ISSUE TITLE
Clicking close on the log window during export throws error, leaves uncertain state

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#247]
Sometimes I reflexively click the close button too early. Errors are thrown and I'm not sure if the export was completed. I generally just run the export again to make sure it completes fully.

POSSIBLE SOLUTION:

Set the enabled property to `False` while the export (or build) is running.

```
Private Sub cmdExport_Click()
    On Error GoTo ErrorHandler
    cmdClose.Enabled = False
    ...<SNIP>...
ErrorHandler:
    cmdClose.Enabled = True
    DoEvents
    
End Sub
```

Additionally, you can intercept the `Form_Unload` event and set the `Cancel = Not cmdClose.Enabled` so that when the close button is disabled, form unloading is also canceled.
https://docs.microsoft.com/en-us/office/vba/api/Access.Form.Unload

I would recommend implementing an error handler that ensures the button is reenabled at the end.

**Comment by hecon5** [comment]
Since I think there's an error handler to deal with the hourglass mouse icon, those could be tied together?

**Comment by joyfullservice** [comment]
I have added in some additional handling to confirm that the user actually intended to cancel the running process if they click the close button or close the form while an export or build is running.

![image](https://user-images.githubusercontent.com/7254992/125126257-6d7a3400-e0c0-11eb-8c24-771c268b2589.png)

![image](https://user-images.githubusercontent.com/7254992/125126276-75d26f00-e0c0-11eb-83f0-d395ee78c0ba.png)

Yes, you can still throw an error if you catch it at just the right moment, but this should handle the majority of the cases when a user didn't realize that the operation was still in process, or if they are using the close button to intentionally stop the process.
