### ISSUE TITLE
Sanitize Comboboxes are empty

### ISSUE THREAD

**Issue by Geforced** [joyfullservice/msaccess-vcs-integration#258]
When i open the options -> Export Tab there aren't any items in both Sanitize Comboboxes.
When i click on one of them there are 4 non visible options. Maybe there is an error with the getting the names function.
If i click on one of these invisible options and try to save the option there is an runtime error "13" type mismatch.

VCS Version: 3.4.15
Access Version: Professional Plus 2016 (2108)

**Comment by joyfullservice** [comment]
Hmm... You should be seeing something like this:

![image](https://user-images.githubusercontent.com/7254992/132747389-14209076-cd2b-43a0-8dfd-2c8322df9615.png)

I am not sure why these wouldn't be loading for you. Is there something special about your environment that could be affecting it? Perhaps try some testing using a blank database in a different folder.

Let me know if you are able to pinpoint anything further with this issue. I haven't seen this before, and I know that a number of other users are successfully using version 3.4.5 of the add-in.

(Also note that you can debug and step through the add-in code as well, if that is helpful in your troubleshooting. You will find the project listed in the VBA IDE after running one of the add-in commands.)

**Comment by Geforced** [comment]
there shouldn't be anything special about my environment. Happening also in an empty database.

I found an old thread, which seems like the same problem:
https://www.access-programmers.co.uk/forums/threads/invisible-text-in-combo-box.197326/
However i couldnt fix it. I tried to set the zero-width bound column to 2cm to search for the error. Now this is shown:
![error (2)](https://user-images.githubusercontent.com/71797991/132766159-85546e83-41bb-4d48-8dc4-890197f2b800.PNG)

(I tried to debug it, but i am not able to find the error or get to the right position)

**Comment by joyfullservice** [comment]
Thanks, the screen shot is actually very helpful! It looks like the values are not being split on the comma. Normally `1` would be the first (hidden) column, and `Basic` would be the displayed text.

Just out of curiosity, what are the locale/language settings on your system? That might possibly affect how the comma is treated...

**Comment by Geforced** [comment]
Yes, thats obviously also the reason why i get the runtime error.

I am working with german locale/language settings on my system as well as in office. 
However if i change the splitting symbol for this combobox from "system symbol" to "," in the formular, then nothing changes.

**Comment by Geforced** [comment]
Okay, if i change the "SeparatorCharacter" from "System" to ";" it will work. But only after i have replaced the "," with an ";" in the Form_Load() in the code. It seems it has something to do with RowSource and the Value List seperating it only with an ";"

Do you have a fix for this which works on all local/language settings? And are you going to make a Hotfix Release soon or should i change it manually on our teams computers?

Thanks for the help

**Comment by joyfullservice** [comment]
I am pretty sure the semicolon works on English systems, but I will need to verify that when I get back to the office tomorrow. If it works with no issues, I may be able to push out an update tomorrow.

**Comment by joyfullservice** [comment]
After doing some testing on my system, I am pretty confident that changing the comma to a semicolon should work. The list shows up correctly for me, even though my language settings technically use a comma as a list separator. This makes me think that the semicolon should work across most if not all language/locale settings. If we run into issues later, we can always explicitly set the `SeparatorCharacter` property on the multi-column combo boxes.

I will upload version 3.4.16 shortly. Let me know if this resolves the problem for you!

**Comment by Geforced** [comment]
Works perfectly. Thanks for the quick help and for the update.
