### ISSUE TITLE
Infinite loop in install if Version Control.laccdb left over in %APPDATA%

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#261]
Low priority, but worth investigating.  This won't happen except in abnormal circumstances.

I tried to run export again using 3.4.16 (I forgot to install the new version).  That hung hard and I had to kill the process, which left a .laccdb in %APPDATA% (unknown to me at the time).

I then tried installing 3.4.17.  It said it was successful, and when I told it to finish (and restart to trust) it hung in an infinite loop testing for the disappearance of the .laccdb file, which wasn't disappearing.  I paused the console with a selection, removed the .laccdb manually, and unpaused, and it finished.

I reran the install to be safe and everything completed normally.

Screenshot of paused loop
![accvcs02](https://user-images.githubusercontent.com/2840152/134793851-150771ea-4f40-4e81-8b90-e5f6f80b3b4e.png)

**Comment by hecon5** [comment]
Looks like need to add a counter to the script. 

By chance, which install options are you using?

**Comment by hecon5** [comment]
Figured it out; inadvertently reset the timer upon starting loop. PR Inbound.
