### ISSUE TITLE
vcs-index.json question

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#265]
Is vcs-index.json required to be committed to git?  Is it used only for fast-save?

It changes on every export and if it's not strictly necessary would it be OK to add it to .gitignore?

**Comment by joyfullservice** [comment]
Yes, you definitely should add this file to your `.gitignore` file, as well as the log files. You can use `.gitignore` file in this project as a template for other database projects.

**Comment by jhgarrison** [comment]
Thanks!
