### ISSUE TITLE
Export "ERROR: Unhandled error found before `On Error` directive" 

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#269]
I made a single change to the database options:  Current Database/Navigation Options/Show System Objects toggled from True to False.

Immediately subsequent export threw an error during "Exporting themes..." but continued.  

See attached export.log

I debugged the code and believe the problem is in either `clsDbTheme::IDbComponent_ClearOrphanedSourceFiles()` or `modVCSUtility::ClearOrphanedSourceFolders(...)`

```
Private Sub IDbComponent_ClearOrphanedSourceFiles()
    ClearOrphanedSourceFolders Me
    ClearOrphanedSourceFiles Me, "thmx"
End Sub
```

The two calls look to me like they are out of order, and attempting to delete the folder before the file causes the Error 70.  

However, in `modVCSUtility::ClearOrphanedSourceFolders(...)` 

```
    ' Remove base folder if we don't have any subfolders in it
    If oFolder.SubFolders.Count = 0 Then oFolder.Delete
```

doesn't check for files, only subfolders. Both of these combine to result in the Permission Denied error.  I'd submit a patch if I had time to figure out the right solution, but am pressed for time.

[Export.log](https://github.com/joyfullservice/msaccess-vcs-integration/files/7369177/Export.log)

Short term workaround is to manually delete the `themes` subdirectory and let the export recreate it.

**Comment by hecon5** [comment]
This is related to #226, in fact, I think it might be the same problem, but we may have misdiagnosed it before potentially.

**Comment by jhgarrison** [comment]
I've created the following commit in my local repo.  Do you want a formal pull request? It's a trivial change.

```
Author: Jim Garrison <bitbucket@jhmg.net>  2021-10-21 18:09:08
Committer: Jim Garrison <bitbucket@jhmg.net>  2021-10-21 18:09:08
Parent: 39f74c342876ba3fbb70908aded563b414489e64 (Fixes @joyfullservice/msaccess-vcs-integration/issues/261 (#262))
Branch: master
Follows: v3.4.17
Precedes: 

    Issue #269 Export "ERROR: Unhandled error found before On Error directive"
    
    Reverse order of two statements in clsDbTheme::IDbComponent_ClearOrphanedSourceFiles
    so that it deletes the files in the themes folder before attempting
    to remove the folder itself.
    
    This was causing Error 70: Permission denied

--------------- Version Control.accda.src/modules/clsDbTheme.cls ---------------
index c034305..8652ff0 100644
@@ -395,8 +395,8 @@ End Function
 '---------------------------------------------------------------------------------------
 '
 Private Sub IDbComponent_ClearOrphanedSourceFiles()
-    ClearOrphanedSourceFolders Me
     ClearOrphanedSourceFiles Me, "thmx"
+    ClearOrphanedSourceFolders Me
 End Sub
```

**Comment by jhgarrison** [comment]
Did this ever get integrated into a release? I'm still having this issue, specifically ONLY with the "themes" directory.  I have to remove the themes directory every time before attempting an export.

**Comment by joyfullservice** [comment]
@jhgarrison - I just checked, and while it has been fixed on the dev branch, it wasn't actually implemented on the master branch, which is what we build the releases from. I will go ahead and make that change now, so it should roll out in the next release. Sorry about that!

As a side note, if you ever need to hot-fix something in the add-in, you can simply open the add-in database file from `Environ$("AppData") & "\MSAccessVCS\Version Control.accda"', make the code changes, the save and close. The next time you use the add-in, it will have your hot-fix changes. That's the nice thing about having this add-in developed as a Microsoft Access database add-in. (Obviously keep in mind that your changes will be overwritten the next time an update is installed.)
