### ISSUE TITLE
Build from source fails VCS 3.4.17 - 'unable to determine database file name'

### ISSUE THREAD

**Issue by alanv73** [joyfullservice/msaccess-vcs-integration#273]
Exported using VCS 3.4.17
no build log created

![image](https://user-images.githubusercontent.com/29257817/138471455-a697d426-5689-4b46-873a-4084bcacc2d6.png)

**Comment by joyfullservice** [comment]
Thank you all for the input on this issue. I was able to reproduce it on my system as well. While the recommended approach for new projects is to use a blank export path, I recognize that some environments and workflows require other configurations, and I think it is reasonable to support these alternate configurations.

I have added an additional `VCS Build Path` property in `proj-properties.json` to correspond with the existing `VCS Source Path` property and built out the functionality to be able to export and build from source when the build location and source path are in different locations. I have successfully tested this using a database on my computer and the source files on a network drive. I also tested to confirm that I can export and build using a _relative_ location in the Export Folder. This should bring us back to the intended functionality described in the [Wiki documentation](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options#export-tab). 👍
