### ISSUE TITLE
Build fails with "Unable to determine database file name"

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#281]
First time trying out Build functionality.  It fails with the following error and leaves the hourglass cursor up.

![accvcs06](https://user-images.githubusercontent.com/2840152/140667702-c4d62d64-2f2b-44ab-a7dd-91f2058486bd.png)

Given the following `vbe-project.json`

```
{
  "Info": {
    "Class": "clsDbVbeProject",
    "Description": "VBE Project"
  },
  "Items": {
    "Name": "Shop User Database",
    "Description": "",
    "FileName": "ShopUsersVer6.00.accdb",
    "HelpFile": "",
    "HelpContextId": 0,
    "ConditionalCompilationArguments": "",
    "Mode": 0,
    "Protection": 0,
    "Type": 100
  }
}
```

I traced into GetOriginalDbFullPathFromSource, the problem happens at:

```
        If Options.ExportFolder = vbNullString Then
            ' Default setting, using parent folder of source directory
            GetOriginalDbFullPathFromSource = strFolder & PathSep & ".." & PathSep & strFile
        Else
            ' Check to see if we are using an absolute export path  (\\* or *:*)
            If StartsWith(Options.ExportFolder, PathSep & PathSep) _
                Or (InStr(2, Options.ExportFolder, ":") > 0) Then
                ' We don't save the absolute path in source code, so the user
                ' needs to determine the file location.
>>>>            Exit Function '<<<--- Exits here leaving return value empty
            Else
                ' Calculate how many levels deep to create original path
                lngLevel = UBound(Split(StripSlash(Options.ExportFolder), PathSep))
                If lngLevel < 0 Then lngLevel = 0   ' Handle "\" to export in current folder.
                GetOriginalDbFullPathFromSource = strExportFolder & PathSep & _
                    Repeat(".." & PathSep, lngLevel) & strFile
            End If
        End If
```

Here's the immediate window with some values:

```
Killed build timer 7501
?options.ExportFOlder
d:\Guild\src\ShopUsersDatabase

?codeproject.FullName
C:\USERS\JIM\APPDATA\ROAMING\MSACCESSVCS\VERSION CONTROL.ACCDA

?strFolder
D:\Guild\src\ShopUsersDatabase\
?strExportFolder

```
Since `Options.ExportFolder` is an absolute path, the method exits leaving the return value empty, which then fails in the caller at

```
    ' Build original file name for database
    If blnFullBuild Then
        strPath = GetOriginalDbFullPathFromSource(strSourceFolder)
        If strPath = vbNullString Then
===>        MsgBox2 "Unable to determine database file name", "Required source files were not found or could not be decrypted:", strSourceFolder, vbExclamation
            Exit Sub
        End If
    Else
```

I don't have enough context to know what the code should be doing here.

**Comment by jhgarrison** [comment]
I successfully built the dev (4.0.0) version following the procedure on the Wiki.

That version fails the same way trying to build my exported database.

**Comment by joyfullservice** [comment]
I recently made some enhancements (#273) to the 4.0 version to help with absolute export paths. It sounds like you were able to build version 4.0 from the `dev` branch, so you will want to install it and then export your project using version 4.0 before the build will work. (Version 4.0 adds an additional database property to track the build path when an absolute export folder is being used.) Issue #273 also goes into some discussion on some suggested alternatives for absolute build paths and the benefits of using a blank or relative build path if you can.

Let me know if your build works after running an export using version 4.0.  😄 

P.S.
Keep in mind that the `dev` version is a work in progress with some fairly significant changes underway. You are welcome to use it on your projects, but know that this is more of a development beta version as we build out some new functionality. (I am using it for some of my projects, but some edge cases might not be fully fleshed out, especially in the area of conflict resolution.)

**Comment by jhgarrison** [comment]
I tried starting an export using 4.0.0 but it brings up the "Conflicts" dialog with 14 entries.

```
Component	FileName
Proj Properties	proj-properties.json
DB Properties	dbs-properties.json
Themes	themes\Office Theme.thmx
Table Data	tables\DBConfig.xml
Table Data	tables\DBInfo.xml
Table Data	tables\Std Coments.xml
Table Data	tables\tblShop Use Reason.xml
Table Data	tables\tblToolList.xml
Table Data	tables\ttbAuthCapability.xml
Table Data	tables\ttbAuthResultCodes.xml
Table Data	tables\ttbLogMessageTemplates.xml
Table Data	tables\ttbOrderItemTypes.xml
Doc Properties	documents.json
Hidden Attributes	hidden-attributes.json
```

Is this an artifact of changes to the table data and metadata export format?

I see that the "Show Diff..." functionality is not implemented yet. 

At this point, which option should I choose, "Skip All" or "Overwrite All"?  Are those options implemented?

**Comment by joyfullservice** [comment]
> 
> Is this an artifact of changes to the table data and metadata export format?

The comparison logic has not yet been implemented for many of the object types, so you will see this prompt at each export.

> 
> I see that the "Show Diff..." functionality is not implemented yet.

Correct. This will eventually open up your selected diffing program (i.e. WinMerge) to highlight the differences.

> 
> At this point, which option should I choose, "Skip All" or "Overwrite All"? Are those options implemented?

Yes, generally so. In the context of an export, Skip means to not export that item, and Overwrite means to overwrite the existing file. (For reference, prior to version 4.0, an export would always overwrite the files.)

If you are wanting to test out and evaluate the build functionality with your project, I would recommend using the latest published release of the add-in with an empty (default) export path. That should give you a good idea of how the export and build process work. (You can always tie into the `AfterExport` hook to have another script copy the exported files to a secondary network location.)

The 4.0 release may be weeks or months away from general release, so you may be better off working with the existing release unless the absolute paths are critical for your development workflow.

**Comment by hecon5** [comment]
@joyfullservice since this is the second issue regarding this, I think we should apply the fix to `master`, and release an updated version for this fix. It appears to be a more common use than we anticipated.

**Comment by joyfullservice** [comment]
> 
> 
> @joyfullservice since this is the second issue regarding this, I think we should apply the fix to `master`, and release an updated version for this fix. It appears to be a more common use than we anticipated.

Yes, I think you are right. We can probably also roll in the hashing update while we are at it.

**Comment by joyfullservice** [comment]
The build path fix and hashing update have been copied over to the `master` branch, and version 3.4.18 has been released. Let me know if you have any issues building from source with this latest version.
