### ISSUE TITLE
Question: invoke MSAccessVCS.RunExportForCurrentDB without reference?

### ISSUE THREAD

**Issue by jhgarrison** [joyfullservice/msaccess-vcs-integration#283]
I'm trying to automate the process of generating a release of MY project.

I figured out how to directly invoke MSAccessVCS.RunExportForCurrentDB but this requires defining a reference to MSAccessVCS, which then gets exported.  When my project is copied to the target system, that reference path will be invalid.

Is there a way to invoke RunExportForCurrentDB without having to define a reference?

**Comment by joyfullservice** [comment]
Yes, actually there is. See the following issue for details:

-  #88 

This allows you to invoke the installed add-in, running it just like you would when clicking the menu item. You will need to add some VBA code to your project, but you don't have to maintain a reference to the add-in.
