### ISSUE TITLE
Option "Export -> Export Folder" isn't saved

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#284]
Hello,

I have downloaded V3.4.18 and opened it via Ribbon -> AddIns -> VSC Options". 
On the "Export" page in the "Export Folder" text box I entered "\src\%dbName%.src\" (from https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Options -> placeholder as example).
After that I click on "Save & Close".
When I open the file "\src\%dbName%.src\vcs-options.json", it has the following content
```
{
  "Info": {
    "AddinVersion": "3.4.18",
    "AccessVersion": "15.0 32-bit"
  },
  "Options": {
    "ExportFolder": "\\src\\%dbName%.src\\",
    "ShowDebug": false,
    "UseFastSave": true,
.........cut..............
```

When I open the options again, the "Export Folder" option is empty. It seems that the "Export Folder" option is not loading correctly.

Strangely, when I enable the "Show detailed output" option, it is saved correctly and loaded correctly from the vcs-options.json file. 
It seems that all options are saved and loaded correctly except "Export Folder".

**Comment by AndreG52** [comment]
Hi,
Just installed it in Access 2021.
I can confirm the problem, whatever I put in the Export Folder Control the application puts an option.json file in the given folder but will put all the data with an options.json file with an empty "ExportFile" entry in the origin \%dbname%.src\ folder
Andre

**Comment by joyfullservice** [comment]
Thank you all for the feedback on this issue! I believe I have corrected the problem and will be publishing a bug fix release shortly.
