### ISSUE TITLE
Contents of table "msysresource" could be exported twice

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-integration#285]
Hello,

the content of the hidden table "msysresource" is exported to the "images" folder, which is really good.
If the user manually adds the "msysresource" table to export under "options "--> "Table Data" --> then the table is also exported to the "tables" folder.

Then when "build from source" there is an error because the folder "images" is first imported into the table "msysresource", and then the table is imported a second time in the step "import tables". --> but the table already exists.

Maybe you could disable the possibility to select the table "msysresource" in "options "--> "Table Data" for export.

Greetings
TanarRi

**Comment by joyfullservice** [comment]
That is a helpful consideration. Generally users should not be attempting to import _**system table**_ data when building from source. Some tables like the ribbons table can be safely imported, but ultimately it is up to the expertise of the developer to understand which system tables could cause problems if they are imported.

Probably the best thing at this point would be an additional note in the wiki documentation.

**Comment by Tanarri** [comment]
A note in the wiki is fine for me.

**Comment by hecon5** [comment]
Made a PR #286 to do this :) 

Let me know what you think!

**Comment by Tanarri** [comment]
@hecon5 
I think it is ok. Thanks!

**Comment by hecon5** [comment]
With the Wiki update merged into `dev` (and presumably soon to the rest of the wiki), looks like we can close this now :)
