### ISSUE TITLE
Error when exporting source code for large query

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#310]
### Discussed in https://github.com/joyfullservice/msaccess-vcs-integration/discussions/309

<div type='discussions-op-text'>

<sup>Originally posted by **StefanB1983** March 10, 2022</sup>
Hi,
I have installed the Version Control System. Looking great and very user-friendly. 
When I export the source code I face on error though about a query that can not be exported. It is a big query with > 1000 lines. Do you know why the error occurs and how I can resolve this?
Kind regards,
Stefan</div>

**Comment by joyfullservice** [comment]
Hi @StefanB1983, I have created an issue for this discussion since it sounds like we might be dealing with a potential technical issue here.

What is the exact error that you are seeing? Is there anything addition in the log file that points to the problem? Any additional clues or screenshots that you can provide will help us understand more about what is happening. I can't think of anything that would prevent a large query from being exported, but I haven't personally worked with one containing over 1000 lines.

**Comment by StefanB1983** [comment]
Hi @joyfullservice , thanks for the fast reply. Indeed forgot to add the printscreen.

Below an image of the error I see when running the export
![image](https://user-images.githubusercontent.com/95248574/157698227-10d2facc-7692-4aa7-b5ae-9efb6cd8053f.png)

What I can see from the export folder is that the .bas file exists for this query, but the .sql file is missing
![image](https://user-images.githubusercontent.com/95248574/157698346-c4e46ffb-cf22-48e2-80b7-49eb7ad317ae.png)

When I run the export with the debug option enabled it stops at the position below. Almost sounds like it is related to the size of the query although when I save the query manually the file size is 34kb.
![image](https://user-images.githubusercontent.com/95248574/157699402-6a6bdbf4-f604-49c2-a294-a0beb5863971.png)

Hope this helps.

Kind regards,
Stefan

**Comment by joyfullservice** [comment]
Hi @StefanB1983,

Thanks for the additional screenshots! Could you make one additional change as well? If you turn on the VBA option to break in class modules, you can see exactly where the export is hitting this error. I think that would point me in the right direction in potentially resolving this.

![image](https://user-images.githubusercontent.com/7254992/157758342-e76df904-37f3-4e8e-b2ee-8e9565daa9fe.png)

Thanks!

**Comment by StefanB1983** [comment]
Hi @joyfullservice ,

When I open the options dialog I have a different setup then yours. Do you know why?

![image](https://user-images.githubusercontent.com/95248574/157834867-489491f3-27bf-4f78-a6a1-af1da90107c8.png)

**Comment by joyfullservice** [comment]
Just to clarify, this is the VBA options dialog in the Microsoft Access Visual Basic Editor, not the add-in options.

**Comment by StefanB1983** [comment]
Thanks that is clear. I have ran it again and now it breaks at the following line of code

![image](https://user-images.githubusercontent.com/95248574/157877772-d6d92a7a-0b30-4ded-92ed-e0852329bb39.png)

**Comment by joyfullservice** [comment]
Thank you! That is where I thought it might be encountering the error. Can you try something else for me? Try running the following code in the VBA immediate window, using the name of your query.

`?CurrentDb.QueryDefs("qryNavPaneGroups").SQL`

![image](https://user-images.githubusercontent.com/7254992/157881586-9c488857-7548-41a6-8da1-3c8143770a32.png)

This will allow us to determine whether the error is coming from Microsoft Access, or from the add-in. If the error is from Access, we may be hitting a system limitation that we can't do much about. (My hunch is that the problem is with the query definition being so large) If this is the case, here are a few things you could consider with your project:

- Simplify the query into multiple queries to reduce the size of the SQL text. I don't know what the query looks like, but perhaps this could be accomplished through some nested queries or by splitting into two or more queries that could be combined with a UNION query.
- You could also turn off the option to save the SQL text of your queries. Personally, I kind of like having the SQL because I find it easier to read the changes in version control, but I don't know what design limitations you are working with in your environment.

I hope this helps!

**Comment by StefanB1983** [comment]
When I run the code I get the following. I guess that means it is a limitation of Access. I will see if we can simplify the query. Thanks for your quick response and help!

![image](https://user-images.githubusercontent.com/95248574/157884808-2468bd2b-2753-4ecf-ba23-c73921db01e0.png)

**Comment by StefanB1983** [comment]
Hi @joyfullservice ,
I have adjusted the query and that indeed resolved the issue. Thanks!

**Comment by joyfullservice** [comment]
> Hi @joyfullservice , I have adjusted the query and that indeed resolved the issue. Thanks!

Glad to hear that! I will go ahead and close out this issue. 👍
