### ISSUE TITLE
Using ampersand (&) in the name of a Table Index hangs VCS 3.4.17 during Export

### ISSUE THREAD

**Issue by alanv73** [joyfullservice/msaccess-vcs-integration#314]
Discovered a scenario where an ampersand (&) was used in the Name of a Table Index and it was causing VCS 3.4.17 to hang during export.

![table_index](https://user-images.githubusercontent.com/29257817/161995936-2a63e90a-6519-4443-98bf-7cf5c547c6fa.png)

**Comment by joyfullservice** [comment]
Added fixes to the `master` and `dev` branches.
