### ISSUE TITLE
Performance Logging Math seems ... off

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#319]
I've been looking at the Perf export/import log details lately, and the math seems to be off. I was wondering if anyone else is experiencing this as well. 

Case in Point, where the total seems to be reported as a negative. As you can see, the "other operations" is negative (and the sum of the above), but the "total" appears to be correct. There are other times where this doesn't seem to affect it, and the total shows up correctly and "other operations" is zero. Any thoughts?

This doesn't affect the build or anything else, was just an odd thing I noticed and have been looking at scratching my head.

I ran the following: 
```VBA 
Public Sub logSpeedTest()
    Dim testIteration As Long
    Perf.Reset
    Perf.ComponentStart "LogSpeedTest"
    For testIteration = 1 To 200
        Log.Add "LogSpeedTest", "Test Log" & testIteration
    Next testIteration
    
    Perf.ComponentEnd
    Debug.Print Perf.GetReports
End Sub

```

```Log
--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Object Type                   Count     Seconds
--------------------------------------------------
LogSpeedTest                  1         0.23
--------------------------------------------------
TOTALS:                       1         0.23
--------------------------------------------------

--------------------------------------------------
Operations                    Count     Seconds
--------------------------------------------------
AddEntry                      200       0.21
Console Updates               3         0.01
--------------------------------------------------
Other Operations                        -0.22
--------------------------------------------------
```

**Comment by joyfullservice** [comment]
@hecon5 - I think the issue here is that to see the overall totals, you need to specify when to start and end the overall timing operation. You will probably also want to time some _operations_ in addition to, or inside the _components_ you are timing. 

I think of components as a larger grouping of different operations. In the case of the add-in, we are talking about exporting specific types of components. If most of the export time, for example, is taken up in Forms and Queries, that is where I will drill down further at the operation level to try to make some performance gains.

Here is what I get after making a couple tweaks to your code:

![image](https://user-images.githubusercontent.com/7254992/165384624-7a66bf7c-95dd-4622-b086-52c3cbc241fb.png)

```
--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Object Type                   Count     Seconds
--------------------------------------------------
LogSpeedTest                  1         0.47
--------------------------------------------------
TOTALS:                       1         0.47
--------------------------------------------------

--------------------------------------------------
Operations                    Count     Seconds
--------------------------------------------------
Iteration                     200       0.47
Console Updates               1         0.00
--------------------------------------------------
Other Operations                        0.00
--------------------------------------------------
```

Hope that helps!

**Comment by hecon5** [comment]
ooh, fascinating... is there any reason the "start timing" can't be auto-run if you call `perf.something` before you `perf.StartTimnig`?

I'm asking because this would allow someone to basically just use the bits that are needed, and if you're not actively timing something, it'd be nice to ignore other stuff

**Comment by joyfullservice** [comment]
Right. I was thinking about that as I was reviewing the code this afternoon. The tradeoff is that additional property access (to verify that the timing has started) on each iteration adds a tiny amount of performance overhead. But the benefits of portability and ease of use probably outweigh the razor-edge difference of adding in the additional property access.

Let me see if I can refactor this a bit, perhaps even adjusting the approach to allow light-weight usage in other applications that might not need the full set of features in every timing operation.

**Comment by joyfullservice** [comment]
Perhaps I should also change _Component_ to _Category_ to make this concept a little more generic for portability reasons.

**Comment by hecon5** [comment]
Agreed, the terminology was the other thing I see my team getting tripped up on when looking things over.

Maybe just a boolean flag within the class that's set or cleared with start or end timing, respectively. While that uses up a minimum amount of memory, it is cheaper to check that than an operation to see if timing started or not...

**Comment by joyfullservice** [comment]
FYI, I have some additional refactoring in progress, but probably won't finish it till tomorrow...

**Comment by hecon5** [comment]
As I was thinking last night on how to best do this, I thought, perhaps there's two ways to use this: 
1. As a standalone process monitor; basically drop this into any old application to monitor performance of items for later troubleshooting. In this aspect, not only are you not really interested in the total time of running (user may have an application open for days or weeks in some cases), that number is ... useless. **You ARE interested in the time spend actually doing operations.**
2. As a condition monitor, like is used with the VCS; basically, you have a Major task (`StartTiming`) and many parts within this task. There are big steps (export a form, for instance), and small steps (build a hash, compare that, convert to UTF-8, etc.). In this case, the total time IS of importance, because there are items which aren't timed, but they still contribute to the total export time (for instance, some file saving operations may not be timed directly with `operations` (they're an OS level thing), but they DO contribute to the total time to export or build a database.

With that, I wonder if there should be two internal flags set; one if you just start timing a `Component`, and one when you just start timing an `Operation` without a component. 

If either of those start without `StartTiming` having been called, we should `starttiming` and `Endtiming` when that respective item finishes. This will ensure that if you do use those without calling start/stop timing, the "other operations" time is zero.

This becomes a bit more complicated because You can have multiple `Components` and many `Operations` within each `component`; or maybe it isn't. 

I'm making a PR to flesh this out, give me a sec.

**Comment by joyfullservice** [comment]
@hecon5 - Yes, I think we were both heading in a similar direction here. Making the class usable for very simple timing operations, as well as more complex comprehensive jobs like we use it during an export or build. I finished out the refactoring I had started yesterday, so you can now use the class in both simple or complex ways.

The following code sample demonstrates both scenarios, with the output shown below:

```vba
Public Sub PerformanceTimingDemonstration()

    Dim lngCnt As Long
    
    With Perf
    
        ' Log minimal test for an operation
        .Reset
        .OperationStart "Single item"
        Pause 0.1
        .OperationEnd
        Debug.Print .GetReports
    
        ' Log minimal test for a category
        .Reset
        .CategoryStart "Generic tests"
        Pause 0.1
        .CategoryEnd
        Debug.Print .GetReports
    
        ' Log a more comprehensive test
        .StartTiming
        .CategoryStart "Doevents Loop"
        For lngCnt = 1 To 100
            .OperationStart "Doevents"
            DoEvents
            .OperationEnd
        Next lngCnt
        Pause 0.1
        .PauseTiming
        MsgBox "User interaction not included in timing", vbInformation
        .ResumeTiming
        .CategoryStart "API Sleep Loop"
        For lngCnt = 1 To 50
            .OperationStart "API Sleep"
            Pause 0.01
            .OperationEnd
        Next lngCnt
        .CategoryEnd
        .EndTiming
        Debug.Print .GetReports
        
    End With
    
End Sub
```

```
--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Operations                    Count     Seconds
--------------------------------------------------
Single item                   1         0.10
--------------------------------------------------


--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Category                      Count     Seconds
--------------------------------------------------
Generic tests                 1         0.11
--------------------------------------------------
TOTALS:                       1         0.11
--------------------------------------------------


--------------------------------------------------
                PERFORMANCE REPORTS
--------------------------------------------------
Category                      Count     Seconds
--------------------------------------------------
Doevents Loop                 0         0.54
API Sleep Loop                1         0.76
--------------------------------------------------
TOTALS:                       1         1.30
--------------------------------------------------

--------------------------------------------------
Operations                    Count     Seconds
--------------------------------------------------
Doevents                      100       0.54
API Sleep                     50        0.76
--------------------------------------------------
Other Operations                        0.00
--------------------------------------------------
```

**Comment by hecon5** [comment]
Testing looks good! I decided to set the `Category` to private and leave the wrapper, while I realize it may cause some slight performance hits, not needing to refactor is a big bonus for me.

**Comment by hecon5** [comment]
This looks good; working on my end mostly. 

One caveat: if you run `.EndTiming`, you'll get negative other operations, I think because of the prior `LapTimer` value.

**Comment by hecon5** [comment]
Found a few more edge cases:
1. On caveat above: I that's a code-quality issue so not much need be done, but could cause confusion.
2. If you `PauseTiming` and `ResumeTiming` without having done start/end timing (eg, if you use this as a generic process monitor and don't want to monitor use of a message box prompt wait), timing will be zeroed out. I'm not actually sure if this is happening, because this is rather hard to test with ye' ole' stopwatch and the times involved, but it's looking possible. Will do some more testing to verify.
3. The `CallStack` is acting weird now. If it's the first time you've run the call stack after stopping the VBA code, `CallStack` will return `vbNullString`. I'm still trying to figure out why; it doesn't seem like it should. 
4. `CallStack` adds a trailing `.` if you don't have an operation running. Looks like detection for operation needs to check operations for not being `vbNullString` as well, I'll make a PR for this. (done)

**Comment by hecon5** [comment]
Figured out item 3 above; if you start a `Category` (or `Operation`) and IMMEDIATELY ask for the call stack, there's a chance the timing hasn't run yet (potential race condition). As a result, there's nothing on the callstack, and it returns `vbNullString` duitifully. 

We'll need to check the `CategoryName` and `OperationName` to ensure they're also `vbNullString` prior to skipping out to ensure `CallStack` Returns correctly.

**Comment by hecon5** [comment]
Figured out a cleaner way to check for lack of call stack and not need to check twice; updated PR with this.

**Comment by joyfullservice** [comment]
Pull request #323 has been merged. Thanks!

**Comment by hecon5** [comment]
I think that's all the issues I found; I'm going to close this now. We can always reopen it if there are other issues. 

Thanks again!
