### ISSUE TITLE
VCS 3.4.21 hangs during full export of database containing tables with data macros

### ISSUE THREAD

**Issue by alanv73** [joyfullservice/msaccess-vcs-integration#325]
I have a test database containing a table with two data macros and two tables with no data macros. 
VCS 3.4.21 hangs during full export.

[test_be_datamacro.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/8604996/test_be_datamacro.zip)

**Comment by joyfullservice** [comment]
Thanks for reporting this! It looks like I need to adjust for the encoding of this type of export file. This caused the file to be read incorrectly, triggering an endless loop when sanitizing the XML. I plan to address both issues, correcting the encoding, and preventing the loop if something like this happens in the future.

**Comment by joyfullservice** [comment]
@alanv73 - Could you confirm that this update resolves the problem?
[Version_Control_v3.4.22.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/8605590/Version_Control_v3.4.22.zip)

**Comment by alanv73** [comment]
I tested it on two of my backend databases that contain data macros and it worked well. I did not test it on a frontend database with forms and modules.
