### ISSUE TITLE
No MSysIMEXSpecs and MSysIMEXColumns tables present in Version Control.accda

### ISSUE THREAD

**Issue by cenx1** [joyfullservice/msaccess-vcs-integration#33]
### Systeminfo

- __Access Version:__ MS Office 365 64bit
- __msaccess-vcs-integration Version:__ 3.1.8

### Details

The project that I am building contains Import/Export Specifications (I think they are called that) and when I am building from source, the step that import the two MSys tables __MSysIMEXSpecs__ and __MSysIMEXColumns__ from Version Control.accda into the new project that it is building, fails because the tables are not present in the add-in.

The error happens in the __clsDbImexSpec__ module in this function:
```vb
Private Sub ImportMissingTableFromAddIn(strTable As String)
    If Not TableExists(strTable) Then
        ' This is were the problem is
        DoCmd.TransferDatabase acImport, "Microsoft Access", CodeProject.FullName, acTable, strTable, strTable, True
    End If
End Sub
```

The Version Control add-in should contain the two tables upon release.

**Comment by joyfullservice** [comment]
Beautiful job reporting this issue! Thanks for taking the time to document this clearly. I was able to push a code change this morning (806e990) that should fix the issue with the missing tables.
