### ISSUE TITLE
Error exporting stdole

### ISSUE THREAD

**Issue by ls-2037** [joyfullservice/msaccess-vcs-integration#348]
Hi,

I get the following error during `Exporting vbe references...`

```
-------------------------------------
Exporting vbe references...   
  stdole

-------------------------------------
ERROR: Unhandled error found before `On Error` directive
-------------------------------------
Error -2147319779: Method 'Name' of object 'Reference' failed Source: Unknown

-------------------------------------
ERROR: Error exporting stdole
-------------------------------------
Error -2147319779: Method 'Name' of object 'Reference' failed Source: modImportExport.ExportSource
[1]
-------------------------------------
No vbe forms found in this database.
-------------------------------------
```

**Comment by joyfullservice** [comment]
Hmm... I haven't seen that one in any of the databases I have worked with. Has it worked before, but suddenly stopped working, or are you trying an export on this database for the first time? Do you have this issue with other databases, or just this particular one?

Another thing you could test is to remove the reference to `OLE Automation`, then add it back in, and see if that resolves the issue. (Make sure you close the dialog between removing and adding it back in.)

Hope that helps!

**Comment by ls-2037** [comment]
> Hmm... I haven't seen that one in any of the databases I have worked with. Has it worked before, but suddenly stopped working, or are you trying an export on this database for the first time? Do you have this issue with other databases, or just this particular one?
> 
> Another thing you could test is to remove the reference to `OLE Automation`, then add it back in, and see if that resolves the issue. (Make sure you close the dialog between removing and adding it back in.)
> 
> Hope that helps!

Thanks. It seems like the error was due to macro execution being disabled for the Access file, as it goes away once it is enabled.
