### ISSUE TITLE
Unicode text not preserved in sanitized UTF-8 source files

### ISSUE THREAD

**Issue by joyfullservice** [joyfullservice/msaccess-vcs-integration#35]
Adding this as a new issue since it is related but different from #30. Here were are dealing with characters in objects like Forms and Reports that are converted from UCS to UTF-8 and back, but losing the Unicode characters. I have confirmed this in the testing database.

![image](https://user-images.githubusercontent.com/7254992/82952383-7f595000-9f6e-11ea-851b-6aae24ad705e.png)

In the image above, neither file is correct. They should have a checkmark character "✔", which ideally should be natively visible in the exported source file.

**Comment by joyfullservice** [comment]
It looks like @cenx1 may have already corrected this on his branch... https://github.com/cenx1/msaccess-vcs-integration/commit/c07655ff95f3bfdf29279ee9191f892fedb84aea

Casper, could you create a pull request for me to pull your changes on modFileAccess into the joyfullservice branch? I like the approach you took there with the two API calls to do the Unicode conversion. (And I don't know of any simpler way to do this.)

**Comment by cenx1** [comment]
Absolutely, I would have done it today, but time was small. I will try and get it done by tomorrow.

**Comment by joyfullservice** [comment]
Awesome!! Thank you so much!

**Comment by cenx1** [comment]
I have added a PR for you with the requested code and some additional change suggestions. Feel free to pick what you think fit this project.  #40 

I think you are doing a good job. 👍

**Comment by joyfullservice** [comment]
This should be resolved as of #41 in release v3.1.26. Thanks again for your work on this!
