### ISSUE TITLE
Bug: Version 4.x ExportAllSource will not export internal changes if external files are edited.

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-integration#364]
If you use "ExportAllSource", select "Overwrite all", and export, files which were edited both inside and outside will NOT be exported. 

To reproduce: 
1. Edit a file in Access and in the development folder.
2. Save the edits in both places.
3. ExportAllSource (either via ribbon or Addin>ExportAllSource, or open VCS and click "ExportAllSource") 
4. Full Export should be cleared.
5. Select "Overwrite All" when prompted.
6. Click Export Continue. 

Your file on the outside will not be exported over. 

This is a serious blocker for 4.x.

**Comment by joyfullservice** [comment]
I stepped through the code on this, and we are just dealing with a bug where the component folder name needs to be included in the path to the source file. Should be a pretty simple fix.

**Comment by joyfullservice** [comment]
This should be fixed now. Thanks for catching that, @hecon5!

**Comment by hecon5** [comment]
Fixed!
