### ISSUE TITLE
Error 2475

### ISSUE THREAD

**Issue by Pixleated** [joyfullservice/msaccess-vcs-integration#367]
Error Dialog
![image](https://user-images.githubusercontent.com/116006068/196201066-b9582053-aeb2-471e-81d6-3a4e87452a83.png)

Code Snippet
![image](https://user-images.githubusercontent.com/116006068/196201223-70c40d47-6652-494a-b844-c332edb73288.png)

Module
Public Function VerifyFocus(ctlWithFocus As Control) As Boolean

Version: 3.4.23
![image](https://user-images.githubusercontent.com/116006068/196201687-96bf1dbb-366c-43f1-9148-87ce05beb908.png)

**Comment by Pixleated** [comment]
Thanks for the tip.

I'm not sure. I tried today without leaving Access and it worked fine.
I'll report back if it happens again.

**Comment by joyfullservice** [comment]
Is this still a problem? If not, we can go ahead and close the issue. Thanks!

**Comment by Pixleated** [comment]
Sorry for late response. I haven't used it for weeks until this week. Keeping the focus on Access doesn't get me an error anymore. Thanks for the tip.
