### ISSUE TITLE
ReadJsonFile fails due to BOM

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#37]
ReadJsonFile is looking at the leftmost character, which might be a BOM. 

![image](https://user-images.githubusercontent.com/26984068/83044510-1ff45200-9ff9-11ea-933d-5b2d1018abbe.png)

JSON files are being written as UTF8 with BOM. We need to account for the possibility that a BOM may or may not exist.

**Comment by A9G-Data-Droid** [comment]
I'm working on a patch with this in it:

```
Public Function ReadJsonFile(strPath As String) As Dictionary
    Dim strText As String
    If FSO.FileExists(strPath) Then
        With FSO.OpenTextFile(strPath)
            strText = RemoveUTF8BOM(.ReadAll)
            .Close
        End With
        
        ' If it looks like json content, then parse into a dictionary object.
        If Left(strText, 1) = "{" Then Set ReadJsonFile = ParseJson(strText)
    End If
End Function
```

**Comment by joyfullservice** [comment]
Nice! Do we need to open the file differently (with the Tristate* flag) if it contains Unicode characters? Might be something to test...
