### ISSUE TITLE
Missing export for form event code

### ISSUE THREAD

**Issue by samsquared** [joyfullservice/msaccess-vcs-integration#373]
### Discussed in https://github.com/joyfullservice/msaccess-vcs-integration/discussions/372

<div type='discussions-op-text'>

<sup>Originally posted by **samsquared** November 30, 2022</sup>
I've successfully installed the add-in (works nicely, thank you) and did an export.  Everything seems to be there except code for my form events.  These appear in VBA under my database, "Microsoft Access Class Objects" with separate modules for each form containing event code with the name Form_myformname.  General VBA code appearing under "Modules" was exported.  Is there another option I need to check?

Thanks.</div>

**Comment by hecon5** [comment]
The form and form code appear in the same folder, just below it. 

Open up "YourDBNName.accdb.src"\forms and open one of the files. The top of the file should be the layout/fields/etc. then later on you'll see something like this.

```VBA
CodeBehindForm`
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
```

**Comment by joyfullservice** [comment]
Yes, exactly. When Microsoft Access exports a form, the form definition and the source code are combined into the same text file. The form definition is on top, and the source code at the bottom of the file. This add-in saves the form source files in `\forms\*.bas`.

**Comment by samsquared** [comment]
Thank you both very much for the quick reply!  Yes, I see the code now.  I'd done a search looking for some specific code but it didn't find it for some reason.  I'll be putting the exports into Perforce (now Helix).

**Comment by hecon5** [comment]
If this is answered, can you close it @samsquared ?

**Comment by samsquared** [comment]
Gladly.  Thanks again.
