### ISSUE TITLE
Run-time error '3075' when checking if table has a data macro

### ISSUE THREAD

**Issue by mwolfe02** [joyfullservice/msaccess-vcs-integration#384]
I'm getting the following error message in the `clsDbTableDataMacro.IDbComponent_GetAllFromDB` function:

![image](https://user-images.githubusercontent.com/305213/223216632-fb810988-65ac-4cca-b440-d78ac82569a0.png)

I seem to be getting the message for every table in my application (or at least the local tables).  I think this may have something to do with my environment, otherwise, this would be an issue for others.  The problematic code has been in place for three years.

VCS Version: **4.0.7**
MS Access Version: Microsoft® Access® for Microsoft 365 MSO (**Version 2206** Build 16.0.15330.20260) **64-bit**

**Comment by mwolfe02** [comment]
Changing the following line of code from...

```
strSql = "Not IsNull(LvExtra) and Type = 1 and [Name] = """ & tdf.Name & """"
```

...to...

```
strSql = "LvExtra Is Not Null and Type = 1 and [Name] = """ & tdf.Name & """"
```

...seems to resolve the problem.

**Comment by joyfullservice** [comment]
That is interesting... It almost seems like the type of error you would get if there was a compile issue elsewhere in the code.  🤔

**Comment by joyfullservice** [comment]
@mwolfe02 - FYI, I am not sure if you are already doing this, but you can clone and build the `dev` branch to pull in all the latest updates. 😄 I also went ahead and pushed out an updated beta release since we have added some more substantial features and fixes since the last one. Let me know how it works on v4.0.9.

**Comment by joyfullservice** [comment]
Cloning and building from source is really easy. I use GitHub Desktop, but any other git client works fine too. The first time you do it, you won't have the binary in the folder, but you can just drop a copy (any version) into the root folder of the project.

1. Close all open instances of Access, then double-click the `Version Control.accda` file to open the add-in. Hit <kbd>esc</kbd> or click the x to close the install window.
2. Click `Build from Source` on the ribbon toolbar, and click OK on the confirmation.
3. After the build completes, close the database.
4. Open the newly built add-in file, and this time proceed with the install. The add-in will close automatically when complete.

And that's it! You now have the very latest version of the add-in installed.  👍 Anytime you want to pull in the latest changes, just run through the four steps above.  😄 (I love version control with Microsoft Access!)
