### ISSUE TITLE
Handling queries that cannot expose SQL

### ISSUE THREAD

**Issue by bclothier** [joyfullservice/msaccess-vcs-integration#391]
Amazing as it may sound, it turns out it _is_ possible to construct a query in such way that it will run just fine but will throw up an error 3258 about ambiguous outer joins whenever the `SQL` property is accessed. That query can be opened normally but cannot be changed over to SQL view. That query can be exported/imported with `Application.SaveAsText`/`Application.LoadFromText` without any issues. It has all the blocks for describing the layout and grid & input tables. It does not contain a `dbMemo` SQL block so the export/import will be OK but this will then fail with error 3258 when exporting the SQL into a separate file. 

My first preference is that this travesty of query should have never seen the light of day. Alas, it is not in my control and to ensure the add-in can support even those queries, it might be worthwhile handling the case during export (and maybe import) so that if the SQL cannot be read event after a successful export to simply skip the SQL export for that troublesome query. 

I also don't think the error really is about ambiguous outer joins because normally, that prevents the query from running at all, and I am pretty sure that such query cannot be exported. The fact that this query does run and can be exported without an error makes me think that there's something wrong with Access' internal parsing when it tries to parse the expressions stored in the query into a SQL statement.

**Comment by joyfullservice** [comment]
Wow, that is quite the interesting scenario! I don't think I have ever personally run into that, but I agree that adding in some error handling around that case sounds like a good idea.

**Comment by mwolfe02** [comment]
@bclothier Do you have an example of such a query that you can provide?  Or is it just something you've come across in the past and don't have ready access to?

**Comment by bclothier** [comment]
I have it with me, yes but unfortunately, I am not comfortable sharing it because it's not mine to share. What I can do instead is give a general description because frankly I am not sure I can replicate this condition but maybe we can in a dummy database but that would also take me considerable time to replicate the query. It might also be dependent on the underlying queries or the table schema, which again take more time to replicate/reproduce.

Some facts:
There are 8 inputs, 5 unique and the other 4 aliased to one same query. The 2 inputs are tables, the rests are other Access queries. One query is the main source and has inner joins to the 2 tables, and then left joins to the 4 other aliased query.
In every left joins between the main query and aliased queries and one other non-aliased query, there are 4 columns (one exception is one with only 3) used in the join expression. In the inner joins between the main query and the 2 tables, there is only one column in the join expression.
It has a complex `WHERE` clause that has 3 controls references to a single form and 5 hard-coded criteria.
There are no `GROUP BY` nor` ORDER BY` defined for this query.

I hope that helps.

**Comment by mwolfe02** [comment]
That sounds like a pretty cornery corner case :joy:

Would you be able to test solutions/workarounds using the query you have without having to share it?  Sounds like it might take more time to reproduce such a query than to create the workaround (not an uncommon situation in debugging, of course...).

**Comment by joyfullservice** [comment]
What about something as simple as this in the query Export function? (Adding the `On Error Resume Next` and watching for the specific error we might hit.)

```vba
    ' If saving in source folder, check SQL option
    If strAlternatePath = vbNullString Then
        ' Export as SQL (if using that option)
        If Options.SaveQuerySQL Then
            Perf.OperationStart "Save Query SQL"
            Set dbs = CurrentDb
            strFile = IDbComponent_BaseFolder & GetSafeFileName(m_Query.Name) & ".sql"
            On Error Resume Next
            WriteFile dbs.QueryDefs(m_Query.Name).SQL, strFile
            If Catch(3258) Then Log.Error eelWarning, "Unable to access SQL property of query: " & m_Query.Name, ModuleName & ".Export"
            Perf.OperationEnd
            Log.Add "  " & m_Query.Name & " (SQL)", Options.ShowDebug
        End If
    End If
```

**Comment by bclothier** [comment]
I now have a different scenario to consider.  

It is legal to create a empty query where the `SQL` is simply just `SELECT;`. Such query can be exported but cannot be imported even though it can be recreated:

```
CurrentDb.CreateQueryDef "qryMuchAdoAboutNothing"
?CurrentDb.Queries("qryMuchAdoAboutNothing").SQL
SELECT;

```

This also can be done interactively by creating a new query, and then immediately save it. It will let you save even though you did not add any inputs to the top pane or set any fields in the grid on the bottom pane. 

Currently, the addin will successfully export that query, but then report an error when importing that query.  Access will also generate an error file with entry:

```
Microsoft Access encountered an error while importing the object 'qryMuchAdoAboutNothing'.

Error encountered at line 2.
Could not create or set the property Connect.
Error encountered at line 4.
Could not create or set the property SQL.
```

The problem I see is that:

* It could be a query that was saved too early, then user made changes but did not save the subsequent changes, leaving behind an empty query. The user probably should delete the query (maybe it was a throwaway one) or fix the query.
* I don't know if there's a scenario where a query could be corrupted in a way that the SQL is lost and reset to the default `SELECT;`. In this case, this should be a huge red flag prompting the user to investigate further. 

Both are an issue that are easier to fix at the export side, rather than at the import side. Therefore I am inclined to have a check during the export and issue a warning? an error? so that it can be then rectified sooner than waiting until the poor sod on the other side ask about this funny query. 

Thoughts?
