### ISSUE TITLE
Build fails if ActiveX are disabled

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#396]
Hello!

I am using the latest ACCDA stable version 3.4.23 on Access 2019. 
But I believe this issue concerns also the dev branch and other Office version.

Lately I was no longer able to build my Access app, even though it used to work and I didn't do any big changes.

When building from source, all local tables import failed with the following error:
```
-------------------------------------
ERROR: Build error in: ...\tbldefs\USysRibbons.xml
-------------------------------------
Error 31521: Impossible d'établir la connexion au serveur. Source: modImportExport.Build
```
In English, the message reads `Error 31521: Cannot establish connection to the server`.

Tracing the issue in the ACCDA, the offending line was [the call to `Application.ImportXML`](https://github.com/joyfullservice/msaccess-vcs-integration/blob/c966b3427d752cb8c82e56c0c2cce6d5af45b362/Version%20Control.accda.src/modules/clsDbTableDef.cls#L370).

I was able to easily reproduce the issue in a blank database and using `Application.ImportXML` with any XML file properly exported.

A quick search on the web led me to this helpful blog post: http://accessblog.net/2012/05/importxml-method-establish-connection.html

Turns out the issue is not with the file, but with the ActiveX Trust Center parameters!

And indeed, recently our security team made changes to the Group Policies (GPO) for Office apps after reviewing with us that it didn't impact our Access app. Since we though that we didn't use any ActiveX controls (some testing confirmed that our app worked well without), they went ahead and disabled ActiveX on all computers.

Of course I didn't think of testing the _tooling_... 😸 

**For reference, here is what they set in the policies regarding ActiveX:**
1. [Administrative Templates (User) > Microsoft Office 2016 > Security Settings > Disable All ActiveX](https://admx.help/?Category=Office2016&Policy=office16.Office.Microsoft.Policies.Windows::L_DisableAllActiveX) to Enable
1. [Administrative Templates (User) > Microsoft Office 2016 > Security Settings > ActiveX Control Initialization](https://admx.help/?Category=Office2016&Policy=office16.Office.Microsoft.Policies.Windows::L_ActiveXControlInitialization) to 6
2. [Administrative Templates (User) > Microsoft Office 2016 > Security Settings > Check ActiveX objects](https://admx.help/?Category=Office2016&Policy=office16.Office.Microsoft.Policies.Windows::L_CheckActiveXObjects) to 2 (Strict allow list)

Note that even though the policy path reads "Office16", all Office above 2016 are also concerned (because MS stopped counting the major version...).

**After playing a little with the various settings:**
- **Disable All ActiveX**: if enabled, `Application.ImportXML` won't work. This policy should be disabled or not set.
- **Check ActiveX objects**: if set to 2 (Strict allow list), `Application.ImportXML` won't work. Setting this policy to 1 (Override IE kill bit list - the default) or 0 (Do not check) or not set is required to make it work.

------------

I think we could check these settings in the registry to alert the user that building won't work if not properly set.

The registry keys to check are:
| Setting name | Registry path | Correct value |
|---|---|---|
| Disable All ActiveX (GPO) | `HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\common\security\disableallactivex` | 0 or not set |
| Disable All ActiveX (Local) | `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Common\Security\disableallactivex` | 0 or not set |
| Check ActiveX objects (GPO) | `HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Common\com categories\checkofficeactivex` | 0 or 1 or not set |
| Check ActiveX objects (Local) | `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\com categories\checkofficeactivex` | 0 or 1 or not set |

@joyfullservice what would be the best place to do this check and alert the user?

Have a nice weekend! 😺

**Comment by joyfullservice** [comment]
Wow, thank you for taking the time to create such a detailed post on this issue! I wonder if we should do the check during the installation of the add-in, and warn the user that they may not be able to build from source with their current security settings.

We could check before each build, but I almost think a better approach is to handle the error with a more descriptive error message that guides them to the source of the problem when this specific error is encountered. I have added some error handling around this scenario in a commit I will be pushing to the `dev` branch shortly.

**Comment by joyfullservice** [comment]
Here is a message I am looking at displaying when a user installs the add-in but has ActiveX disabled.

![image](https://user-images.githubusercontent.com/7254992/232161889-d63accdd-11d1-42e5-931c-e693d9817ab5.png)

We can tweak the wording as needed, but this should go a long way in helping users understand why building from source might not work in a more locked-down environment.

**Comment by Indigo744** [comment]
@joyfullservice thank you, this is very good as usual! I couldn't have think of a better way 👍 

With all that, the next impacted user will directly know/understand the issue and will be able to quickly work around it!

In the install warning message, should we add a link to a wiki page explaining the settings/policies/registry keys needed for it to work? Or maybe in the [FAQ section](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/FAQs).

**Comment by joyfullservice** [comment]
Thanks for the suggestion! I was able to put together a new page on the Wiki describing some of the [Security Considerations](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Security-Considerations) when installing and using the add-in. My hope was to provide a resource for network and systems administrators to understand what the add-in does, and what security requirements are needed for it to function. It also explains the potential security risks of things like building a database from source without reviewing where the source code came from.

Hopefully this will be a help to some people out there. Feel free to suggest any tweaks or changes.

**Comment by Indigo744** [comment]
This is very thorough. Good job!

This issue can be closed 😺 thank you!
