### ISSUE TITLE
Configuration not saved

### ISSUE THREAD

**Issue by marshall-ucsd** [joyfullservice/msaccess-vcs-integration#53]
v3.1.51 - Fresh installation; Office Pro 2016, Win10 Pro, all current patches.
When I make any changes in the Options dialog, they are not saved (or restored). Export Folder is just one field. demonstrating the problem:

1. Open VCS Options dialog
1. Enter a value in Export Folder ("source" in my setup)
2. Click Save & Close
3. Close Access
4. Re-open Access (same database)
5. Return to the Options dialog - Export Folder is blank again. Other fields also revert to their defaults.

This is reproducible.
The database I am using this on is an existing Access database, that I've been using timabell's VCS version with, if that might be relevant.

**Comment by joyfullservice** [comment]
Thanks for reporting this! I am able to reproduce the same behavior on my end.

Just to clarify, are you wanting to export to a specific folder other than the default `/[Database Name].src/`?

**Comment by marshall-ucsd** [comment]
Correct - With the timabell fork, the exported source code went into the `/source/` folder, and I'd like to maintain that setup for my project's existing Git repository.

On a related note, it would be helpful if the wiki documented where configuration data is stored, as that needs to be detailed in our own projects' documentation.

**Comment by joyfullservice** [comment]
Just a quick update... I hope to have this resolved tomorrow.  😄

**Comment by joyfullservice** [comment]
This should be resolved as of version v3.1.54. I will go ahead and close this issue, but please feel free to reopen it if you encounter further problems.  👍

**Comment by joyfullservice** [comment]
Also, in answer to the question of where the options are saved, I have made some pretty extensive updates to the wiki today, detailing each of the options and noting that the options are saved in `vcs-options.json` in the export folder. I hope that helps!
