### ISSUE TITLE
Security option = None triggers error on closing options dialog

### ISSUE THREAD

**Issue by marshall-ucsd** [joyfullservice/msaccess-vcs-integration#54]
v3.1.51, Access 2016
In Options, if you select Security=None (should be default?), the Encryption tab is (partially?) hidden, but you still get an "Encryption Key Not Set" error when you Save & Close the options dialog.
If you select NO, proceeds as expected. But if you select YES, you're returned to the Options dialog but you cannot set an encryption key.
Expected behavior: No error, of course.
Workaround: Select NO to the error. Not sure if there are side-effects from that action.

**Comment by joyfullservice** [comment]
Good suggestion. I have set the default to NONE, and fixed the encryption warning to only show if you are using encryption.
