### ISSUE TITLE
Build from source is unable to determine database file name

### ISSUE THREAD

**Issue by bgsmase** [joyfullservice/msaccess-vcs-integration#55]
Installed release 3.1.51.

Created blank database with Access 2019.

Used ExportAllSource with Encryption set to "none".

Ran "Build from Source" from same database and accepted the default options for the source files.

Get a dialog box with the message:

> Unable to determine database file name
> Required source files were not found or could not be decrypted:
> W:\ ...snip... \mytest\test.accdb.src\

On examination of the source I see this comes from modFunctions.bas - Fuction GetOriginalDbFullPathFromSource trying to read the database filename from the Items\FileName attribute in vbe-project.json which has been created as an empty string by the ExportAllSource process. I'm not sure whether it is intended that the exported source should contain a file name by default or whether it would be better for the build from source process to default to using the current open database name as the default?

**Comment by joyfullservice** [comment]
Can you give this a try again using the latest release of v3.1.54? I am able to successfully build a test database without any issues by either opening the test database and selecting **Build From Source** or by opening Microsoft Access and building it directly from the folder of source files. I also tested building the database from the source files after deleting the original database, and this worked correctly as well.

I believe this issue has been resolved as of the latest release, but please feel free to reopen the issue if you are still having problems.

**Comment by bgsmase** [comment]
v3.1.54 makes no difference for me.

Note I am testing using a blank newly created database having installed the add-in from the releases zip. I can't use the Testing/Testing.accdb database for other reasons (Run-time error '3170': Could not find installable ISAM) but I guess that is something else to do with the specific content of that testing database.

I notice that  [vbe-project.json](https://github.com/joyfullservice/msaccess-vcs-integration/blob/68543146cca9b369582e1ec9cea285d091617ff7/Testing/Testing.accdb.src/vbe-project.json#L10) in the Testing.accdb.src directory has `"FileName": "rel:Testing.accdb"` but if I use the ExportAllSource from my own database the FileName is empty. Then I get the error mentioned above when trying to Build from Source. If I manually edit the vbe-project.json file to add a FileName like `"rel:test.accdb"` (the name of my test database) then I can Build from Source successfully.

**Comment by joyfullservice** [comment]
Thanks for the additional information! I am having difficulty reproducing the problem on my system, but I think you are on the right track in pinpointing the missing file name in `vbe-project.json`.

There is a function to pull the relative file name of the `VBProject` in relation to the file name of the database, but this _should_ be the same as the database name. (Unless somehow we got the wrong `VBProject` connected with the current database.)

```
Private Sub IDbComponent_Export()

    Dim dProject As Dictionary
    
    ' Read project properties
    Set dProject = New Dictionary
    With dProject
        .Add "Name", m_Project.Name
        .Add "Description", m_Project.Description
        .Add "FileName", GetRelativePath(m_Project.FileName)   '  <-- Sets file name
        .Add "HelpFile", m_Project.HelpFile
        .Add "HelpContextId", m_Project.HelpContextId
        .Add "Mode", m_Project.Mode
        .Add "Protection", m_Project.Protection
        .Add "Type", m_Project.Type
    End With
    
    ' Save in JSON format.
    WriteJsonFile Me, dProject, IDbComponent_SourceFile, "VBE Project"
    
End Sub
```

I have made some changes to ensure that `GetRelativePath` always returns a value, so that will take care of the blank value, but as to the underlying issue of why the CurrentProject.FileName isn't matching CurrentDB.FulllPath, I am wondering if there might be a [macro security setting](https://www.mrexcel.com/board/threads/trust-access-to-the-vba-project-object-model.1110756/) that is not allowing access to the VBA project object model.

See if you have an option to _Trust access to the VBA project object model_ under _Macro Settings_ in your Microsoft Access options. With this option checked, are you then able to export the project file name?

**Comment by bgsmase** [comment]
I don't have the `Developer Macro Settings` section or `Trust access to the VBA project object model` checkbox in my Trust Center -> Macro Settings. Using Access 2019.

**Comment by bgsmase** [comment]
I get the yellow message bar `SECURITY WARNING Some active content has been disabled. Click for more details.` when I first open a new database but I can click the `Enable Content` button. I had been using databases on a Network Drive, in which case I get a follow up message `Do you want to make this file a Trusted Document` to which I reply Yes.

I next tried creating a database on a local drive where I get the first security warning but not the question about making the file a Trusted Document. Doing an ExportAllSource from the database on a local drive resulted in the "FileName" being entered in the vbe-project.json file :-)

After that I tried setting the network location of my network drive to be a trusted location and the not recommended option of allowing trusted locations on network but this did not work.

The network location is a mapped drive on our corporate LAN.

So I've narrowed it down to being databases on a network drive where it doesn't work but not sure what a suitable fix is?

**Comment by joyfullservice** [comment]
Thanks for the tip on the network drive! I was able to reproduce the issue now, and will be working on a resolution...

**Comment by joyfullservice** [comment]
I have just uploaded a new release (v3.1.55) bab569b that should fix this issue. Let me know if you have any further problems!

**Comment by bgsmase** [comment]
Thanks that has fixed the unable to determine database file name problem.

(Now I have a new problem building from source but I'll make a separate issue for that :-) )
