### ISSUE TITLE
Custom export folder = export fails - Runtime error 91

### ISSUE THREAD

**Issue by marshall-ucsd** [joyfullservice/msaccess-vcs-integration#56]
v3.1.54, Access Pro 2016
Running an export generates a Runtime 91 error, which on debug jumps to ModImportExport, Line 106. 
The object name is "Office Theme", FWIW
I restarted Access and tried again - same error.
I was using a custom folder name ("source"), which apparently triggered the problem. If I use the default (none), export works.
I assumed (incorrectly?) that having an export folder of "source" would place files in the (existing) folder DBFOLDER\source, where DBFOLDER is the folder the .accdb file lives in. Some additional validation or documentation may be needed, if I'm using that field incorrectly.

**Comment by marshall-ucsd** [comment]
Addendum: Using "source" for export folders put everything in c:\User\USERNAME\source, which was not expected. 
It was exporting the "Office Theme", which is strange (why would it need to export that at all?)
So, should export folder be an explicit full path?

**Comment by joyfullservice** [comment]
Try using `\source` as the export folder name. (Note the preceding backslash.)

**Comment by marshall-ucsd** [comment]
Specifying the full path also works correctly, so there is a simple workaround.

**Comment by joyfullservice** [comment]
I just updated the [documentation ](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Documentation )with some examples on how to use the export folder name. Thanks for pointing that out!

As to the themes being exported, some people use custom themes in their Microsoft Access applications to give a more unified appearance. It's just one part of where a database might be customized. See #48 for more details.

**Comment by joyfullservice** [comment]
Is this working for you now? If so, feel free to close this issue.  😄
