### ISSUE TITLE
UseFastSave skips table data

### ISSUE THREAD

**Issue by A9G-Data-Droid** [joyfullservice/msaccess-vcs-integration#58]
I added some debugs around `HasMoreRecentChanges`  and I found that the `DateDiff` command is returning a positive number of seconds that has elapsed between the two modified dates. This large positive number will never be smaller than -3.

I verified that the `SourceModified` is correct. It's the `DateModified` that is wrong. I modified the table today and yet the debug output is showing 4/10/2020 2:08:48 PM

**Comment by joyfullservice** [comment]
Nice catch! The code was looking at the modification of the table structure, which of course has nothing to do with when the actual data was modified.  😄
