### ISSUE TITLE
Unable to install the add-in: missing USysRegInfo table

### ISSUE THREAD

**Issue by junpet** [joyfullservice/msaccess-vcs-integration#59]
I wanted to install the add-in, but I got the following error.
![image](https://user-images.githubusercontent.com/3465278/88474520-96dd9680-cf27-11ea-9d74-0c345bd3f26e.png)

Access Version:
![image](https://user-images.githubusercontent.com/3465278/88474589-5af70100-cf28-11ea-89ba-84d1f6c7c30e.png)

![image](https://user-images.githubusercontent.com/3465278/88474603-76620c00-cf28-11ea-9566-ab80c21223ba.png)

This is my personal home PC. So I have administrator rights. I can help to debug the error, just say what to do. I've never used any add-in before, but I'm familiar with VBA.

**Comment by m8e** [comment]
AFAIK this code is only compatible with Microsoft Access 2010/2013/2019

**Comment by joyfullservice** [comment]
It sounds like you might be trying to install it from the Add-in menu, which requires a `USysRegInfo` table. I used to do it this way, but this requires admin rights for the install. Now the add-in is self-installing and does not require admin rights. Just download the latest release from the [Releases](https://github.com/joyfullservice/msaccess-vcs-integration/releases) page, and double-click to run the file. It should install itself automatically.

This add-in should run in any version of Microsoft Access version 2010 or newer. Let me know if you are able to install it by running the `Version Control.accda` file.

**Comment by junpet** [comment]
@joyfullservice Thanks, I could install by running the `Version Control.accda` file.
