### ISSUE TITLE
Issues to re-build Access file with data

### ISSUE THREAD

**Issue by anbrikzone** [joyfullservice/msaccess-vcs-integration#61]
Hi!
I'm very appreciate for this Add-in! It's awesome! Thank you very much for your work!

I faced with some problems when I want to restore Access file with data:
1. If data was exported in Tab format (in XML format - everything OK), when it rebuilding, the program is crashing with error on this line:
`rst.Fields(varHeader(intCol)).Value = varLine(intCol)`
in Class Module "clsDbTableData"
I suppose it happens because there is problem with variables type.
2. When i re-built Access file with data I found some strange issue - all fields has the same format type - Text (in Access 2010) or ShortText (in Access 2016).
It is OK if our sources doesn't content any data. In this case all fields have right format type.
3. And last one - in your form **frmVCSOptions** the combobox **cboTableDataSaveType** has data in RowSource. And when form is loading in the list appear twice items.

If i can help with something i will be pleasure.

**Comment by joyfullservice** [comment]
I am glad to hear that you find the add-in useful! let me make a few brief comments in reply to your questions:

1. I recommend XML format if you are wanting to rebuild the table data from source. The tab-delimited format is more designed for review in the source code repository. The XML has a lot more of the details needed to recreate the data structure in the proper form.

2. This sounds like it might be related to the question above. Does it work fine when using XML format?

3. Thanks for pointing this out! It has actually already been corrected, and will be included in the next release.

**Comment by anbrikzone** [comment]
1. Ok. I got it.
2. I re-build Access file from data of tables, which were exporting in XML Format before. After re-build all fields has the same Data Type - Short Text.
3. Thank you.

**Comment by effjot** [comment]
When importing my test DB, data types work correctly when importing from Tab-delimited files. On the other XML works better when international characters / umlauts are involved, but sets all column types to “short text”.

In clsDbTableData, Sub `IDbComponent_Import`, the import of XML is handled by `Application.ImportXML`. The documentation for import option `acStructureAndData` says: “Imports the data into a new table based on the structure of the specified XML file.”  But the XML file has no “structure” information (except the column names), so I guess “short text” is the default for unspecified data types.

I have changed the import option to `acAppendData` and commented out deleting the table. Then the table is imported correctly. I’m not sure about other effects of this change.

**Comment by effjot** [comment]
I used `acAppendData` and it seems to work. I’ll test it more thoroughly, but you can already have a look at https://github.com/effjot/msaccess-vcs-integration/commits/joyfullservice_fj

I’m not sure if deleting/truncating the table is necessary. It should be empty when building from source, right?

**Comment by effjot** [comment]
The current `master` still imports everything as text. I have merged in my changes (see comments from 11 and 17 September above): https://github.com/effjot/msaccess-vcs-integration/tree/joyfullservice_fj

I’m going to test it for a while and then prepare a pull request.

**Comment by Indigo744** [comment]
@effjot if you open a PR with your change, I could also test it and report back.

**Comment by joyfullservice** [comment]
I believe this has been resolved, but if not, please feel free to reopen the issue.
