### ISSUE TITLE
cmd commands

### ISSUE THREAD

**Issue by manasimahajann** [joyfullservice/msaccess-vcs-integration#62]
Hello,

Thank you for your help with version control on Access.

We were wondering, if there is a 'command prompt' set of commands we could use to do this faster.

Thank you,
Manasi

**Comment by joyfullservice** [comment]
After the add-in is loaded, you can type `ExportSource` in the VBA immediate window to run the export. Is this what you are looking for?

**Comment by manasimahajann** [comment]
Hi Adam,
Thanks for your quick response.
yes, that worked!
Thank you,
Manasi

**Comment by joyfullservice** [comment]
Glad to hear it!
