### ISSUE TITLE
Run-time error '3021': No current record

### ISSUE THREAD

**Issue by jschof** [joyfullservice/msaccess-vcs-integration#66]
I get this when I **_Export All Source_** from the Version Control form.

**Fails in:** modImportExport.ExportSource
**cCategory.Category**= "shared images"
**At Line:** cCategory.Count 

I can then continue to run the code and it is proceeds fine but getting that error each time I export is annoying.

**Update:** I get this message repeatedly when I **_Export All Source_** directly from the add-in (vs from the Version Control form):

```
Public Function AddInMenuItemExport() As Boolean
    PreloadVBE
    Form_frmVCSMain.Visible = True
    DoEvents
    Form_frmVCSMain.cmdExport_Click <--------------------------
    AddInMenuItemExport = True
End Function
```

**Environment**:
Windows 10
Access for Microsoft 365
MSAccessVCS 3.1.56

**Comment by joyfullservice** [comment]
@jschof - Thanks for reporting this issue! Could you go the VBA Options, and make sure the error handling is set to Break in Class Modules? That will help pinpoint exactly where this error is being triggered.

![image](https://user-images.githubusercontent.com/7254992/94734994-aca87700-032f-11eb-9079-9a8d49b67b34.png)

I am getting ready to update the installer, so this would be a great time to add another bug fix to include in the next release.

**Comment by jschof** [comment]
With the new error trapping setting I managed to figure out where the problem was:

![MsAccessVCS](https://user-images.githubusercontent.com/15448821/94736952-0e221300-033b-11eb-9542-3d48aa087e6e.png)


As it turns out one of the images was missing!?!

![MSysResources](https://user-images.githubusercontent.com/15448821/94741335-fc903980-0341-11eb-931e-7926f967b389.png)

I added the image and then ran into another error! Turns out that I had multiple images with the same name which is accepted in MSysResources but not in the class module clsDbSharedImage:

```
Private Function IDbComponent_GetAllFromDB() As Collection

    Dim cImg As IDbComponent
    Dim rst As DAO.Recordset
    Dim strSql As String

    ' Build collection if not already cached
    If m_AllItems Is Nothing Then
        Set m_AllItems = New Collection
        
        ' This system table should exist, but just in case...
        If TableExists("MSysResources") Then
            
            Set m_Dbs = CurrentDb
            strSql = "SELECT * FROM MSysResources WHERE Type='img'"
            Set rst = m_Dbs.OpenRecordset(strSql, dbOpenSnapshot, dbOpenForwardOnly)
            With rst
                Do While Not .EOF
                    Set cImg = New clsDbSharedImage
                    Set cImg.DbObject = rst    ' Reference to OLE object recordset2
                    m_AllItems.Add cImg, Nz(!Name)  <---------------------------------
                    .MoveNext
                Loop
                .Close
            End With
        End If
    End If

    ' Return cached collection
    Set IDbComponent_GetAllFromDB = m_AllItems

End Function
```

So I 1) added the missing image, and 2) renamed the duplicate image and can now export without error :-)

Thanks for pointing me in the right direction!

**Comment by joyfullservice** [comment]
Nice work!! Was the duplicate image name caused by VBA code, or when adding the image manually? In my experience it seemed that Access would automatically rename the image to keep it unique, but if we might have duplicate names, I probably should use a different key when adding it to the collection, or just skip the key altogether.

**Comment by jschof** [comment]
It was definitely done manually but not sure exactly where nor how I managed to have a duplicate name because when I try to rename an existing image from the Design ribbon it errors with "The resource name 'XYZ' is already in use."

I recently upgraded to this version from 2013 so perhaps there was a problem in that version?

At any rate probably best to just skip the key altogether since it appears you shouldn't run into that situation.

**Comment by joyfullservice** [comment]
I removed the index assignment in 040b5d2. Thanks for pointing this out!
