### ISSUE TITLE
Error 70 "Permission refused" when attempting to install ACCDA file

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#68]
Hello,

When I'm trying to install the ACCDA file, I get the following error:
![image](https://user-images.githubusercontent.com/7137528/96376759-170b4500-1181-11eb-824c-dd3385d40cb2.png)

I am using Access 2016 (French) 32 bits (Office Pro Plus)
![image](https://user-images.githubusercontent.com/7137528/96376785-428e2f80-1181-11eb-854b-2069ee8a0efd.png)

There are no special permission on this folder. I can access / modify it without being admin.

I tried running from an Access as administrator with same result.

I tried to copy the file by hand to %APPDATA% folder but when launching, it does nothing (I guess it detects that the source and dest are the same?).

Please advise? Thank you 😺

**Comment by Indigo744** [comment]
Alright, so I fired up [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and I saw that there was actually a `SHARING VIOLATION` occurring **not** on the destination file or folder, but **on the source file**!
![image](https://user-images.githubusercontent.com/7137528/96377865-c39cf500-1188-11eb-90d9-654a88a554ae.png)

So after thinking about it, I though that the issue could come from the way the ACCDA file is open. Access can open a file in two mode: shared or exclusive. The latter means that nobody else can use the file while it is open in Access.

I went to the Access options and found the default opening mode, it was set to _Exclusive_.
I changed it to _Shared_ and the installation went without issue!
![image](https://user-images.githubusercontent.com/7137528/96377963-4a51d200-1189-11eb-8d80-c716bed1fa15.png)

It is set to _Exclusive_ by our own Access app.

I would recommend to check and set this option before trying to install the addin. 
It can be set with:
```
Application.SetOption "Default Open Mode for Databases", 0
```

I _think_ the database needs to be restarted for the option to apply.

**Comment by joyfullservice** [comment]
Thank you very much for the suggestion, and for so clearly outlining what needed to be corrected. I was able to implement this change today. Since it is a lower impact change, I will just let it roll out the next time I publish a release.
