### ISSUE TITLE
"Build from source" silently fails

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#69]
Hello,

I can export the full app successfully:
```
-------------------------------------
TEST.accdb
VCS Version 3.1.67
Using Fast Save
19/10/2020 18:33:01
-------------------------------------
Exporting themes...           [1]
Exporting VB project...       [1]
Exporting vbe references...   [4]
Exporting proj properties...  [1]
Exporting shared images...    [8]
Exporting db properties...    [54]
Exporting tables...           [206]
Exporting queries...          [304]
Exporting forms...            [245]
Exporting macros...           [25]
Exporting modules...          [23]
Exporting reports...          [155]
Exporting table data...       [1]
Exporting doc properties...   [3]
Exporting nav pane groups...  [1]
-------------------------------------
Done. (47,9 seconds)
```

But when selecting "Build From Source", the build starts, I can see the new file being created, then... nothing?
The mouse pointer stays in "hourglass" mode but nothing seems to happen, and MSACCESS.exe is not really doing anything.

![image](https://user-images.githubusercontent.com/7137528/96488957-10430780-123f-11eb-96ed-e9000ed5d5da.png)

![image](https://user-images.githubusercontent.com/7137528/96488804-deca3c00-123e-11eb-82ef-014d3c1df9d9.png)

![image](https://user-images.githubusercontent.com/7137528/96488821-e558b380-123e-11eb-999d-d917f2ca3d49.png)

**Is there any way I can get a better log for debug or something?**

Thank you 😸 

---
EDIT : I can see an Export.log files, but there is no Import.log at this time...

**Comment by joyfullservice** [comment]
@Indigo744 - The way the add-in works is that it loads on demand into the the Microsoft Access application, similar to the internal Access wizards. The difference though is that the Version Control add-in is not locked or protected, so you can see all the source code, and even set breakpoints and step through the code in the add-in.

To debug an issue when building from source, I would start with a couple things. First, when you are at the screen where it doesn't seem to do anything, try pressing ctl+break on the keyboard, and see if this breaks into the code execution. This is helpful for situations like endless loops. After you get into the code, and see the current line highlighted in yellow, use the F8 key to step sequentially through the code. You can hover over variables to see their values, or use any of the other VBA debugging tools.

Keep in mind that while you can debug and even change code in the add-in, those changes are discarded when the add-in is closed. (Even if you click "save" in the VBA code module.) It is a great way to test out small changes, but remember that the changes in the add-in are not saved when the application is closed. (Unless the add-in is opened directly.)

If the ctl+break doesn't bring you into the code window, you can open the VBA editor and set breakpoints for the code to stop at various places. This should allow you to jump into the execution process and step through the sections leading up to the trouble spot. Based on the output that you were seeing, I would probably try putting a breakpoint at line 215 of `modImportExport`, then step through the code from there. I assume you are familiar with debugging VBA code, but if not, there are some good tutorials and videos online that can help you get started.

There is a log file named `Import.log` in the source folder that might contain a little more information than the GUI display.

As to the underlying issue, one possibility is that it could be related to a language or path issue. I have found that certain functions have better support for Unicode or international language characters. Let me know if you are able pinpoint the issue through additional testing on your side.

Hope that helps!!

**Comment by Indigo744** [comment]
Thank you, I was able to do some quick debugging.

I _think_ I found the culprit: a local table with antislashes in the name (like `hello/world`) which seems to fail when looking for the file (which seems to have `%2F` in the name). I'll try to make a minimum ACCDB file...

**Comment by Indigo744** [comment]
yup that's it. Simply create a new ACCDB file, add a table named `Table/Test` then export. There is a `Table%2FTest.sql` and `Table%2FTest.xml` created in `tbldefs`.
Building from source, it fails in [`modImportExport` line 252](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/modImportExport.bas#L252). By doing a step-through, it fails exactly in [`clsDbTableDef.bas` line 339](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbTableDef.bas#L339)
```vb
Application.ImportXML strFile, acStructureAndData
```

The surprising thing is that `strFile` contains the right value:
```
?strFile
C:\path\to\VCS-TEST\VCS-TEST-IMPORT.accdb.src\tbldefs\Table%2FTest.xml
```

It fails with error 31527 _"path not found"_ (or something similar, it's in French for me).

**Comment by joyfullservice** [comment]
Interesting. Looks like `Application.ImportXML` doesn't do well with UrlEncoded file names... Perhaps this is because XML is often used with Web, and there might be something that converts the `%2F` to a forward slash, which would cause it to no longer see the file path. 

Just for testing purposes, I tried replacing the `%` with `^` and then it imported just fine. Perhaps I need to rethink how to handle characters that can be used in object names, but are not valid in (Windows) file names. I had gone with the UrlEncoding approach because it seemed more standard and intuitive than arbitrary Unicode replacements.

Maybe the best approach here is to continue to use the UrlEncoding technique, but swap the `%` with `^` just before importing... I am open to suggestions on this one.  😄

**Comment by Indigo744** [comment]
Or maybe use a "custom UrlEncoding" like using caret instead of percent to escape chars all the way?
I mean, exporting with `^2F` and reading back `^2F`.

It would simply be a matter of updating the functions `GetSafeFileName` and `GetObjectNameFromFileName`...

However, that would be an issue for backward compatibility I guess...

**Comment by Indigo744** [comment]
Or, and I'm thinking out loud here, what about _not escaping_ but removing all offending chars, and instead keeping a JSON linking the real name and the filename? That way, the filenames are always safe and simple, and the exact object name is properly kept...

I don't know. Maybe it's too much trouble to be worth it...

**Comment by Indigo744** [comment]
If you want to keep backward compatibility at all cost (and avoid adding a migration steps), the simplest approach would be to rename the file with caret escaping (in a temp folder?) before importing it. There would be a performance penalty, but not _that_ much I suspect. However, if something happen and an error is printed, people could be surprised to see a filename (with caret) that does not seems to really exists...

**Comment by joyfullservice** [comment]
Yes, that's kind of what I am leaning towards... Copying to a temp file using the caret name, and import from that. It is only used in a couple places right now, so I don't think it would clutter things up too much.
