### ISSUE TITLE
"Build from source": encoding issue with USysRibbons table

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#71]
Hello,

**Steps to reproduce:**
1. Create an empty ACCDB file
1. Add a `USysRibbons` table (with Id, RibbonName and RibbonXml fields)
1. Add a new line and define a proper ribbon XML **with label containing accented characters** (see [MS article](https://support.microsoft.com/en-us/office/create-a-custom-ribbon-in-access-45e110b9-531c-46ed-ab3a-4e25bc9413de))
   ![image](https://user-images.githubusercontent.com/7137528/96504043-72f2ce00-1254-11eb-958b-1671f101abf9.png)
1. Export as VCS
1. Build from source
1. Restart application and see encoding issues
   ![image](https://user-images.githubusercontent.com/7137528/96504132-9289f680-1254-11eb-894e-0fdd6d9c51ef.png)

The file `tables\USysRibbons.txt` is properly exported in UTF8 with proper accents.
![image](https://user-images.githubusercontent.com/7137528/96504327-ce24c080-1254-11eb-9401-e0f58c4e5be3.png)

The issue arise when importing it.

Thank you.

**Comment by Indigo744** [comment]
Here is a ZIP file containing a working ACCDB with `USysRibbons` table for you to test it.
[TEST-USYSRIBBON_Original.zip](https://github.com/joyfullservice/msaccess-vcs-integration/files/5404328/TEST-USYSRIBBON_Original.zip)

**Comment by Indigo744** [comment]
I took some time to do a step through and [the issue is here](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbTableData.bas#L147) (some lines hidden):

```vb
Private Sub ImportTableDataTDF(strFile As String)
    
    ' ...

    ' Read file line by line
    Set stm = FSO.OpenTextFile(strFile, ForReading, False)

    ' ...

    Do While Not stm.AtEndOfStream
        strLine = stm.ReadLine  ' <------- strLine contains weird chars

        ' ...

    Loop

    ' ...

End Sub
```

It seems that the FSO lib doesn't handle well UTF8 chars.

[This article](https://developer.rhino3d.com/guides/rhinoscript/read-write-utf8/) says:
> The File System Object, generally used by VBScript developers to read and write text files, can read only ASCII or Unicode text files. You cannot use it to read or write UTF-8 encoded text files.

A solution would be to use ADO stream like this:
```vb
Dim objStream, strData
Set objStream = CreateObject("ADODB.Stream")
objStream.CharSet = "utf-8"
objStream.Open
objStream.LoadFromFile("C:\Users\admin\Desktop\test.txt")
strData = objStream.ReadText()
```

**Comment by joyfullservice** [comment]
Nice catch. Looks like this function needs to be updated to use the fully Unicode aware file reading/writing functions that are used elsewhere in the system.

**Comment by joyfullservice** [comment]
Also, I wanted to point out that XML will be a much more robust way to import table data. There is some limited support for importing a TDF file, but the primary purpose of the TDF is for readability in version control.

**Comment by Indigo744** [comment]
Alright, then the default should reflect that? Right now, TDF is the default...

**Comment by joyfullservice** [comment]
You are correct that the `USysRibbons` table is exported as TDF by default in the `clsOptions` class. I had never encountered the encoding issue because I hadn't used any Unicode text in my ribbons, so I am glad you pointed this out.

As to the format, we can use either TDF or XML for these system tables, but my thought was that the readability was better for these system tables in version control using the TDF format. I describe the formats in a little more detail in the [documentation](https://github.com/joyfullservice/msaccess-vcs-integration/wiki/Documentation) page, so hopefully that helps users make a good choice for their needs. Simple content works great in TDF, but for more complex needs, XML might be a better choice.

**Comment by Indigo744** [comment]
Ah, I can see that I can changed the export format for USysRibbons in the config tabs. That'll do I think 😸 

Thank you so much for all your work!

**Comment by joyfullservice** [comment]
With the changes that I made to the TDF import function in bd7cf2d, I would be curious if it resolved the Unicode characters issue when importing data from a TDF file. Is that something that would be easy for you to test?

**Comment by Indigo744** [comment]
Sure I'll test and report back 😸

**Comment by Indigo744** [comment]
I can confirm it works with unicode characters now 👍 thank you!

**Comment by joyfullservice** [comment]
Awesome! Thanks for testing that! It is nice to have it working for others that might use it in the future.
