### ISSUE TITLE
Cannot build ACCDA file from source

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#73]
Hello,

I am using **Access 2016 32-bits French**.

I am trying to build the ACCDA file from source in order to work on it. I'm following the [CONTRIBUTING guidelines](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/CONTRIBUTING.md#development-version).

Howerver, it fails at setting a DB property in [clsDbProperty.bas#L136](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbProperty.bas#L136) with error **_3001 "Invalid argument"_**
- `varKey` = `CollatingOrder`
- `varValue` = `1033`
- `dbs.Properties(varKey).Value` = `1036`

The value `1033` that needs to be set comes from the [dbs-properties.json#L69 file](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/dbs-properties.json#L69), and corresponds to `dbSortGeneral`.

The value `1036` that is already set by default corresponds to... _I actually don't know_ since there aren't any `dbSort*` constant with this value. A quick search on the Internet leads to this [ExpertExchange thread](https://www.experts-exchange.com/questions/26356668/How-do-I-read-set-Application-GetOption-New-database-sort-order-from-ASP.html):
> For example 1033 is “general”, **1036 is “French”**, and 133124 is “Chinese, stroke count”

So I guess it makes sense since I am using a French version... But [the MS documentation](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/collatingorderenum-enumeration-dao) doesn't say anything about it 😞 

I couldn't find any more information on why setting the CollatingOrder to dbSortGeneral would fail in a French version... 

I've seen that this property was mention in https://github.com/joyfullservice/msaccess-vcs-integration/issues/39 and looking at the "new database sort order" it says rightly "French":
![image](https://user-images.githubusercontent.com/7137528/96619913-0258b980-1307-11eb-9049-2fd7cc00a6ca.png)

**Comment by Indigo744** [comment]
In any case, I wonder if:
- this property should be backed up in VCS?
- this property should be set back when building from source? Wouldn't it fails for most?

**Comment by joyfullservice** [comment]
Are you able to _change_ the database sort order in a database? I am not seeing any option to do that, so I am wondering if this is something that doesn't need to be changed or applied when building from source.

What do you think about excluding this property when setting the database properties? It is probably fine to export, and could potentially be helpful to be aware of in VCS, but not something that we need to explicitly set when building a database from source.

**Comment by Indigo744** [comment]
The [MS documentation](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/database-collatingorder-property-dao) actually says it is a read-only property, so I guess we should probably ignore it when building from source, like you said.

I'll try to provide a PR since this seems not that hard (I have more trouble with the whole DevMode/printer settings...).
