### ISSUE TITLE
XML table data import fails with memo fields

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#80]
Hello,

 I have found another issue related to the XML table data format when importing.

To reproduce the issue, simple create a table with a field of type "memo" (or "long text", I don't know the exact wording in English).
Put in this table any text longer than 255 chars (which is the max size for "short text" type).
Set the option to export this table as XML.

When building from source, it fails with an 31550 "importing error":
![image](https://user-images.githubusercontent.com/7137528/97087231-d69c4300-1628-11eb-93df-d8d4fceb9890.png)
A table should be added "Import errors" containing more details. You should see the aforementioned field saying "truncated field", which means there isn't enough space in the field to fill the value from the XML.

Now after looking through the code, I think I understand why.
1. First, the table definition is loaded from the `tbldef\*.xml` file which contains the exact structure
   See [clsDbTableDef.bas#L351](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbTableDef.bas#L351)
1. Stopping here and looking at the table, we can see that the field type is properly set.
1. Next, the table content is loaded from the `tables\*.xml` file which contains the actual content.
   See [clsDbTableData.bas#L269](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbTableData.bas#L269)
1. The error happens here

The thing is, the correct table that was created from `tbldef` is deleted when loading from XML ([clsDbTableData.bas#L271](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/modules/clsDbTableData.bas#L271)) before loading again the other XML file.

However, since the XML file from tabledata doesn't define any structure information (such as types), the field is created as "short string" and importing a value longer than 255 fails.

I'm not sure how we can fix this issue with XML format for table data.

Removing the line that deletes the table doesn't solve anything.

It seems that if we export as XML, there should be only one file with either the structure or the structure AND the data. We can't have the structure only in tbldefs and the data only in tables as XML.

What do you think?

**Comment by effjot** [comment]
See the related issue #61 – everything is created as text because after freshly creating the tables according to the tabledefs, they’re dropped again.
I have removed dropping the table and just filling in the data from XML. So far it works alright with number types. You can try if your problem is solved by this, too: https://github.com/effjot/msaccess-vcs-integration/tree/joyfullservice_fj

**Comment by Indigo744** [comment]
Ah thank you @effjot. I should have searched a bit better before opening a new issue!

You are right, simply commenting the table deletion + using acAppendData solves the problem I was having.

I'm closing this issue and I'll wait for your PR 😺 Thanks again!
