### ISSUE TITLE
Apostrophe in table name

### ISSUE THREAD

**Issue by effjot** [joyfullservice/msaccess-vcs-integration#83]
Export of tables fails if the name contains apostrophes.

I‘ve addded a fix to export and TDF table data import (https://github.com/effjot/msaccess-vcs-integration/tree/export-import-tablename-with-apostrophe), which seems to work.
Such names are a bit deep in Bobby Tables land… Other quoting issues still may lurk somewhere else. Probably it’s better to not allow apostrophes at all.

I only stumbled across it after forgetting to delete an “import failures” table Access puts in the DB when import from Excel etc. fails.

**Comment by joyfullservice** [comment]
Thanks for pointing this out! I have updated several places in the code, and tested some interesting table and field names...  😄 

![image](https://user-images.githubusercontent.com/7254992/97649052-56a91b00-1a24-11eb-93e6-555ad773071f.png)

Let me know if you encounter any further issues of this kind.

**Comment by effjot** [comment]
You’ve missed the 2 places I had fixed, though. ;-)
I’m preparing a pull request.
