### ISSUE TITLE
Error 76: "Path not found" on exporting Query

### ISSUE THREAD

**Issue by TheBooley** [joyfullservice/msaccess-vcs-integration#84]
Hi @joyfullservice 

when exporting any query, I get error 76 / path not found

In sub "ExportSource()" on "cDbObject.Export"

For example
`SELECT tblArtikel.*
FROM tblArtikel
WHERE (((tblArtikel.KzAktiv)=True))
ORDER BY tblArtikel.Text;
`

Tryed with and without an entry in "Export Folder".

Last entry in log window:
![image](https://user-images.githubusercontent.com/5145923/98398937-03594d00-2062-11eb-804f-f7153bbaa656.png)

Office Version: 16.0.12527.21236
Version Control System: 3.2.0

Please less let me know if you need more information.

BR
Markus

**Comment by joyfullservice** [comment]
Thanks for reporting this! I need to add a line of code to verify that the folder exists before moving the item to that location... I should be able to release fix this afternoon. If you want a quick patch, just add the following line to a function in `modFunctions`.

![image](https://user-images.githubusercontent.com/7254992/98400594-e4d75f80-2029-11eb-8181-a47ef592388e.png)

**Comment by joyfullservice** [comment]
@TheBooley - This should be all fixed now. I have added another release (v3.2.1) that includes this fix and a few other enhancements.

**Comment by TheBooley** [comment]
Great! Version 3.2.1 works like a charm.
Thank you for the quick help.
