### ISSUE TITLE
Display table list with the same order as Access

### ISSUE THREAD

**Issue by Indigo744** [joyfullservice/msaccess-vcs-integration#85]
Hello!

I noticed something: Access sorts the table according to its own way, which seems System, Local, then attached table.

The tables listed in the option windows are sorted alphabetically.

Do you think it would be possible to use the same sorting order as Access? It would be way easier to find local tables (which are the one we want to usually export the content).

Thank you.

**Comment by joyfullservice** [comment]
One idea would be to add a [Unicode icon](https://emojipedia.org/globe-showing-americas/) before the table name....

![image](https://user-images.githubusercontent.com/7254992/98742544-3d816200-2374-11eb-9e28-276579e59cf4.png)

We could try to pick something that would best represent each type of table.

- System table
- Local table
- Linked table

Access doesn't have a built-in way to integrate icons in the ListBox control, but using Unicode characters is one way to make the lists a little more interesting. To add a Unicode character, you need to add the surrogate pair, which you can look up on [this site](https://www.fileformat.info/info/unicode/char/1f30e/index.htm).

![image](https://user-images.githubusercontent.com/7254992/98743087-1aa37d80-2375-11eb-8dd4-9aa28343776b.png)

In VBA, you would implement it like this:

![image](https://user-images.githubusercontent.com/7254992/98743209-4292e100-2375-11eb-92c2-87b054d0abbb.png)

Feel free to play around with different icons, and let me know what you would suggest. I kind of feel like we should use icons if we are going to sort the list by sections.

**Comment by Indigo744** [comment]
Seems good! I agree with you.

When playing around with the code, I noticed it's fairly hard to identify local table.
Around here: [frmVCSOptions.bas#L3298](https://github.com/joyfullservice/msaccess-vcs-integration/blob/master/Version%20Control.accda.src/forms/frmVCSOptions.bas#L3298)

Checking local table is easy with `TableDefs` since the `.Sql` property can be used. 
But with info from `AllTables`, I'm not sure how.

The `.Attributes` undocumented property is the only one we could use, but... I couldn't find any proper constant for local table. 
In my DB, I have some local table with `0` as attributes, but also `8`...
I guess we should check if NOT `dbAttachedODBC` and NOT `dbAttachedTable`? Would it be enough? I'm not too sure.
