### ISSUE TITLE
clsDbRelation Import 

### ISSUE THREAD

**Issue by coderGoneOffRoad** [joyfullservice/msaccess-vcs-integration#89]
Found a bug in this class. When importing table relation for a table having composite key and two relations, the import fails because it would try to import only one of the relations. Fixed this by moving the "rel.Fields.Append fld" inside the For-loop.

![image](https://user-images.githubusercontent.com/73994727/99073121-fab2ca80-25bd-11eb-9695-bbccf10d9d97.png)

**Comment by joyfullservice** [comment]
Thanks for pointing this out! I have implemented the fix in the core, and it will be included in the next release.
