### ISSUE TITLE
Object Library not registered

### ISSUE THREAD

**Issue by Geforced** [joyfullservice/msaccess-vcs-integration#96]
When a colleague wants to Build a Database from source he gets an Run-time error -2147319779 (8002801d) saying "Object library not registered". After a small debug session i think the problem has something to do with the Excel reference or so. Is it possible to add a small notification when you are importing your files and some references have a problem. Maybe you can pick the right one directly. The Problem is only happening on his PC. My Version works totaly fine. 
We both use the same Plugin Version which is  3.2.1. 
His Office is 2010. Mine is 2016.

**Comment by joyfullservice** [comment]
Great suggestions! I can probably add something there to better handle errors with references not found.

The case with the Excel reference version difference sounds like a great spot to add an automatic version adjustment in `clsDbVbeReference.AddFromGuid`. If you could post the output of `references.json` on both machines (2016 and 2010) when the reference is set correctly, I would be happy to add this adjustment to the code.

**Comment by joyfullservice** [comment]
I think I was able to figure out the correct versions for this to work. The 6209993 update should roll out in the next release. Let me know if you still encounter any problems with this!  😄
